cmd/prometheus/main.go
storage/interface.go
tsdb/chunkenc/ooo.go
tsdb/chunkenc/ooo_test.go
tsdb/db.go
tsdb/head.go
tsdb/head_append.go
tsdb/head_test.go
tsdb/head_wal.go
tsdb/ooo_head_read_test.go

Opening this for easy comparison and comments. https://github.com/grafana/mimir-prometheus/pull/146 will be updated eventually.
cc @Dieterbe

#146 version one: ganesh-style

---

.github/workflows/golangci-lint.yml
.github/workflows/test.yml
discovery/xds/kuma_test.go
template/template.go

Attemps fixing linting issues on main and related branches

Fix linting errors

---

tsdb/chunks/chunks.go
tsdb/head_read.go
tsdb/ooo_head_read.go
tsdb/ooo_head_read_test.go

Few improvements for the ChunkReader implementation that come from the pairing session with Dieter.

ChunkReader improvements

---

tsdb/head_append.go
tsdb/head_wal.go
tsdb/record/record.go

After the pairing session with Dieter and Ganesh here is a small PR with
some suggestion changes and comment updates.

Suggestions for mmap markers after pair session

---

prompb/types.pb.go
prompb/types.proto
tsdb/agent/db.go
tsdb/agent/db_test.go
tsdb/agent/series.go
tsdb/head_append.go
tsdb/head_test.go

This includes, among other changes, the bugfix for chunks overflow:
https://github.com/prometheus/prometheus/pull/10607

Update prometheus to `af0f6da5`

---

model/labels/matcher_test.go
model/labels/regexp.go
tsdb/db.go
tsdb/head.go
tsdb/head_test.go

**DO NOT SQUASH. MAKE A MERGE COMMIT.**
A routine sync. There are conflicts at this point.

Merge main branch into the out-of-order branch

---

tsdb/db_test.go

Covers the following points in https://github.com/grafana/mimir-prometheus/issues/237
* M-map files are cleared properly
* Querying works properly after compaction
* With level 1 blocks before overlapping compaction
* After overlapping compaction
* OOO Compaction runs right after normal Head's compaction and does not trigger if normal head is not compacted

Improve test coverage for out-of-order head's compaction

---

tsdb/db_test.go

Takes care of this point in https://github.com/grafana/mimir-prometheus/issues/237
*  Corruption in M-map and replay

Add test for replay of corrupted m-map file for ooo data

---

tsdb/chunks/chunk_write_queue.go
tsdb/chunks/queue.go
tsdb/chunks/queue_test.go

This PR updates out-of-order with the changes in main
**MERGE USING A MERGE COMMIT, NOT A SQUASH**

Update out of urder with main 

---

tsdb/db.go
tsdb/db_test.go
tsdb/head.go
tsdb/head_append.go
tsdb/head_test.go
tsdb/head_wal.go
tsdb/ooo_head_read.go
tsdb/wal/wal.go

We believe wbl meaning write behind log is explicit enough so we dont need to
prefix it with ooo.

Rename ooo_wbl to wbl

---

tsdb/db_test.go
tsdb/head_wal.go

We were not updating the MinOOOTime and MaxOOOTime after a replay. The tests did not catch it before because the default values made the querier pick the ooo head. But if any sample comes in, it is possible it can skip ooo head in valid cases. Now in the tests I am explicitly checking for those values to be correct.

Update MinOOOTime and MaxOOOTime properly after restart

---

tsdb/db.go
tsdb/db_test.go

Closes https://github.com/grafana/mimir-prometheus/issues/295

Replay WBL even if OOO Time Window is 0

---

tsdb/block_test.go
tsdb/querier_test.go

The changes to the `BenchmarkQueries` simulate a situation where the out of order time window is small enough for OOO samples to only overlap with the Head block and not the persistent blocks. This can show the query overhead if some % of samples turned out to be out of order from the total samples. I will post results of the benchmark as a comment to this PR.
Edit: note that this benchmark is for fetching the raw sample from the TSDB and not the final PromQL query.

Include out of order samples in BenchmarkQueries

---

model/textparse/protobufparse_test.go
promql/engine_test.go
storage/interface.go
tsdb/head.go
tsdb/head_append.go
tsdb/head_test.go

_This is to the sparsehistogram branch_
Also comment out histogram validation in the TSDB because in Mimir the same checks are already run in the distributor.

Update upstream prometheus/sparsehistogram

---

tsdb/db.go

Remove unused field (forgot to do that in https://github.com/grafana/mimir-prometheus/pull/311)

Remove unused tsdb.Options.NewChunkDiskMapper field.

---

tsdb/compact.go

Simply removes an err check that is not needed anymore.

Remove useless err check

---

model/labels/matcher.go
tsdb/head_append.go

Restore an upstream comment that was deleted by mistake probably.
Fix reference to Mimir.

Comment fixes

---

tsdb/querier_test.go

https://github.com/grafana/mimir-prometheus/issues/367
Signed-off-by: Justin Lei <justin.lei@grafana.com>

Add tests for query sharding

---

tsdb/db.go

tsdb: Fix typo in comment

---

discovery/legacymanager/manager.go
discovery/manager.go
docs/configuration/configuration.md
scrape/scrape.go
scrape/scrape_test.go
storage/series_test.go
tsdb/chunkenc/histogram.go
tsdb/head_append.go
tsdb/head_wal.go

Update to https://github.com/prometheus/prometheus/commit/e6f84d5445c9c89a6d755885acfdc4bcdadab9fa
To get https://github.com/prometheus/prometheus/pull/11856

merge upstream main

---

.github/workflows/sync-fork.yml

Should be able to create upstream to main merge PR.
Uses https://github.com/marketplace/actions/fork-sync  for creating PR
Uses octokit , e.g. https://octokit.github.io/rest.js/v19#repos-get
Signed-off-by: György Krajcsovits <gyorgy.krajcsovits@grafana.com>

Use tgymnich/fork-sync to create PR from upstream merge

---

model/labels/regexp.go
model/labels/regexp_test.go

Oleg suggested in #430 to write a fuzzy test for the regexp optimizations and it opened a Pandora's box. I found multiple issues, which I will try to address 1-by-1. In this PR I'm addressing a bug occurring in `containsStringMatcher.Matches()` when there are multiple occurrences of a substring inside the text to match against. In this case, we have to try to match it against all substrings (stopping as soon as we find a valid match), and not just stopping at the first one.
- Regexp: `.+foo.+`
- Text: `foofoo0`
With the code in `main`, the `FastRegexMatcher.MatchString()` return false, while it should return true. The reason why it returns false is because the code in `main` only check the 1st occurence of the substring `foo` inside `foofoo0` (for which the regexp doesn't match because of …

Fix containsStringMatcher.Matches() when the text contains multiple occurrences of a substring

---

model/labels/regexp.go
model/labels/regexp_test.go
promql/parser/parse_test.go

We have a customer running many queries with label matchers like `label=~".*"`, causing about 20% of ingesters CPU being spent in `FastRegexMatcher.MatchString()`. I want to look if we can optimise it, I started to look at `strings.ContainsRune()`  and ended up with a path I wasn't expecting, which is what I'm proposing in this PR. The performance benefit is not huge, but given doesn't make the logic more complicated, I think we could give it a try.
In this PR:
- Compile the `MatchString()` function. The idea is that we don't have to go through all the `if` statements if the only optimization we have is the `stringMatcher`.
- Replace `anyStringMatcher` with specialised matchers. Each matcher has less checks to do than before.
- Replace `strings.ContainsRune()` with `strings.IndexByte()`. …

Optimize regex star operation

---

tsdb/errors/errors.go

Reverts grafana/mimir-prometheus#460
I'll send an upstream PR, and cherry-pick those commits here, to ensure we have the same commits.

Revert "Implement Is() for multierrors"

---

model/labels/regexp_test.go

While working on further optimizing regex matcher based on real world queries, I've found `TestAnalyzeRealQueries` being very useful. In the last few hours I've further improved it to compute more statistics and in this PR I'm proposing to upstream them. For each regexp found in the logs, it prints
- Parsing time
- Whether it's optimized or not
- Num split queries
- Num sharded queries
- Min/avg/max query start time difference, between consecutive queries (to understand if any cache with a low TTL would be effective or not)

Improve TestAnalyzeRealQueries

---

model/labels/matcher.go
model/labels/matcher_test.go
model/labels/regexp.go
model/labels/regexp_test.go

public
make isRegexOptimized public for issue grafana/mimir#4638
Signed-off-by: dhanu <andreasdhanu@gmail.com>

make isRegexOptimized public

---

CONTRIBUTING.md
discovery/kubernetes/node.go
model/labels/labels.go
model/labels/labels_string.go
scrape/scrape_test.go
tsdb/db.go

From https://github.com/prometheus/prometheus/commit/24d7e5bd49dd26a45c2123a897c6cac5ac7c47f0
No conflicts

Sync upstream 28 apr 2023

---

storage/series.go
storage/series_test.go

From https://github.com/prometheus/prometheus/commit/0d049feac760444cbbafadbe8794843a6f47dba4
To get https://github.com/prometheus/prometheus/pull/12185

Second sync from 28-apr-2023

---

storage/interface.go
storage/merge.go
storage/merge_test.go
storage/series.go
storage/series_test.go
tsdb/querier.go

See https://github.com/grafana/mimir/pull/5369.

Add `ChunkCount()` method to `ChunkSeries`

---

storage/merge.go
storage/merge_test.go
storage/series_test.go
tsdb/chunkenc/float_histogram.go
tsdb/chunkenc/float_histogram_test.go
tsdb/chunkenc/histogram.go
tsdb/chunkenc/histogram_meta.go
tsdb/chunkenc/histogram_test.go
tsdb/chunks/chunks.go

Bring in two fixes, one of a wall corruption:
https://github.com/prometheus/prometheus/pull/12838
and one for a more subtle inconsistency in the counter reset handling:
https://github.com/prometheus/prometheus/pull/12779

Sync with promtheus/prometheus at 83891135c (2023-09-19)

---

promql/functions.go
promql/testdata/native_histograms.test

To not hold up mimir-prometheus update
More discussion in CNCF chat:
https://cloud-native.slack.com/archives/C02KR205UMU/p1706198311136139

Get fix https://github.com/prometheus/prometheus/pull/13474 early

---

tsdb/head.go
tsdb/head_test.go

related to https://github.com/grafana/mimir/issues/7976

head: provide series ID in ForEachSecondaryHash

---

promql/engine.go
promql/engine_test.go
storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw_test.go
storage/remote/otlptranslator/prometheusremotewrite/timeseries.go
tsdb/chunkenc/bstream.go
tsdb/chunkenc/bstream_test.go
tsdb/chunkenc/chunk.go
tsdb/chunkenc/chunk_test.go
tsdb/chunkenc/float_histogram.go
tsdb/chunkenc/histogram.go
tsdb/chunkenc/xor.go

Upgrade to latest upstream ([0ba747187da2313f8673088ae2673ca7a178a2f7](https://github.com/prometheus/prometheus/tree/0ba747187da2313f8673088ae2673ca7a178a2f7)). There are no changes relevant to Mimir AFAICT.

Sync w/ upstream

---

docs/configuration/configuration.md
model/labels/matcher.go
model/labels/matcher_test.go
model/relabel/relabel.go
promql/parser/printer_test.go
tsdb/index/index.go
tsdb/index/index_test.go
tsdb/index/postings.go
tsdb/index/postings_test.go
tsdb/querier.go
tsdb/querier_test.go
util/testutil/context.go

To get https://github.com/prometheus/prometheus/pull/14096

merge upstream at fdaafdb041

---

tsdb/index/postings.go

Get fix https://github.com/prometheus/prometheus/pull/14103

merge upstream at 179163a4c6

---

tsdb/index/postings.go
tsdb/index/postings_test.go

This backports https://github.com/prometheus/prometheus/pull/13286 to the `weekly-r290` branch here.

[weekly-r290] Reduce locking on mempostings delete

---

tsdb/postings_for_matchers_cache.go
tsdb/postings_for_matchers_cache_test.go

Cherry pick https://github.com/grafana/mimir-prometheus/pull/644 into r290

Cherry pick #644 into r290

---

tsdb/postings_for_matchers_cache.go
tsdb/postings_for_matchers_cache_test.go

Cherry pick #644 into r291

---

storage/remote/write_handler_test.go
tsdb/index/postings.go
tsdb/metadata_test.go
tsdb/querier.go

PR for the metalabels hackathon. We want to build a very simple metadata store in prometheus but I figured in order to do it it would be helpful to have a couple of unit tests that simulate what we want to do. We can also allow them to fail while we fix it!
There are two unit tests one that is end to end going from the remote write package and another on the tsdb.

Metalabels: Initial tests

---

model/labels/meta.go
storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
storage/remote/write_handler_test.go
tsdb/head.go
tsdb/head_read.go
tsdb/metadata_test.go
tsdb/querier.go

Working queries for meta label matchers

---

tsdb/compact.go

While diagnosing https://github.com/prometheus/prometheus/pull/14584, the logging of chunks found to be out-of-order during ingester head compaction was lacking some useful information such as series labels.
If the chunks are `safeHeadChunk` it would print labels, but in the case I analyzed they were ordinary mmapped chunks.
So, this PR makes it log the labels that `PopulateBlock` has.
Refactor slightly to avoid logging blanks where information is unavailable.
(This function is only in mimir-prometheus, not upstream)

TSDB: improve debug logging in compaction

---

tsdb/head.go
tsdb/head_append.go
tsdb/head_read.go
tsdb/head_test.go
tsdb/head_wal.go

Revert https://github.com/prometheus/prometheus/pull/14525 on top of the commit used by r303.

Weekly r303 without series shard bug

---

tsdb/head.go
tsdb/head_append.go
tsdb/head_read.go
tsdb/head_test.go
tsdb/head_wal.go

Revert https://github.com/prometheus/prometheus/pull/14525 on top of the commit used by r304.

Weekly r304 without series shard bug

---

tsdb/head.go
tsdb/head_append.go
tsdb/head_read.go
tsdb/head_test.go
tsdb/head_wal.go

Revert https://github.com/prometheus/prometheus/pull/14525 on top of the commit used by r302.

Weekly r302 without series shard bug

---

CHANGELOG.md
cmd/prometheus/main.go
storage/remote/otlptranslator/prometheusremotewrite/helper.go
storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
storage/remote/otlptranslator/prometheusremotewrite/histograms_test.go
storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
storage/remote/otlptranslator/prometheusremotewrite/number_data_points_test.go
storage/remote/otlptranslator/prometheusremotewrite/testutil_test.go
storage/remote/write_handler.go
storage/remote/write_test.go
web/api/v1/api.go
web/api/v1/errors_test.go
web/web.go

Ref: https://github.com/grafana/db-upstream-squad/issues/555
Backport of PRs
https://github.com/grafana/mimir-prometheus/pull/684
https://github.com/grafana/mimir-prometheus/pull/685

303 otlp ct

---

tsdb/head_test.go
tsdb/ooo_head_read.go

Pick upstream https://github.com/prometheus/prometheus/pull/14874

Pick pr14874

---

CHANGELOG.md
cmd/prometheus/main.go
storage/remote/otlptranslator/prometheusremotewrite/helper.go
storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
storage/remote/otlptranslator/prometheusremotewrite/histograms_test.go
storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw_test.go
storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
storage/remote/otlptranslator/prometheusremotewrite/number_data_points_test.go
storage/remote/otlptranslator/prometheusremotewrite/testutil_test.go
storage/remote/write_handler.go
storage/remote/write_test.go
web/api/v1/api.go
web/api/v1/errors_test.go
web/web.go

Updates weekly-r305 branch (just created from commit bf5bf35a1b4d, [used in Mimir r305](https://github.com/grafana/mimir/blob/r305/go.mod#L281)) with changes in weekly-r304 branch.

Update weekly r305

---

CHANGELOG.md
cmd/prometheus/main.go
storage/remote/otlptranslator/prometheusremotewrite/helper.go
storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
storage/remote/otlptranslator/prometheusremotewrite/histograms_test.go
storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw_test.go
storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
storage/remote/otlptranslator/prometheusremotewrite/number_data_points_test.go
storage/remote/otlptranslator/prometheusremotewrite/testutil_test.go
storage/remote/write_handler.go
storage/remote/write_test.go
web/api/v1/api.go
web/api/v1/errors_test.go
web/web.go

Merge `weekly-r305` branch into `weekly-r306` branch, used by Mimir r306.

Update weekly r306

---

storage/remote/otlptranslator/prometheusremotewrite/helper.go
storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go

Cherry-pick 716e912e6726b4ede06333d7eafe955502da7917 into weekly-r307

OTEL logging: add log when adding extra sample, log metric type too.

---

promql/engine_test.go
storage/buffer.go
storage/buffer_test.go
storage/series.go
tsdb/chunks/samples.go
tsdb/head.go

This PR cherry-picks https://github.com/prometheus/prometheus/pull/15025.

Cherry-pick #15025 from upstream

---

tsdb/db_test.go
tsdb/head_test.go
tsdb/ooo_head_read_test.go
tsdb/querier.go
tsdb/testutil.go

Pick https://github.com/prometheus/prometheus/pull/15180

pick upstream pr15180

---

storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
storage/remote/otlptranslator/prometheusremotewrite/histograms.go

Applying #719 to r310

---

storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
storage/remote/otlptranslator/prometheusremotewrite/histograms.go

Applying #719 to r311

---

storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
storage/remote/otlptranslator/prometheusremotewrite/histograms.go

Applying #719 to r312

---

tsdb/postings_for_matchers_cache.go

We shouldn't call `span.AddEvent()` with `PostingsForMatchersCache` lock taken. It keeps the lock for longer, for no good reason.

Do not call span.AddEvent() with PostingsForMatchersCache lock taken

---

tsdb/index/postings.go

See: https://github.com/grafana/pir-actions/issues/238

[weekly-r312] Cherry-pick Prometheus PR 15242

---

tsdb/index/postings.go

See: https://github.com/grafana/pir-actions/issues/238

[weekly-r313] Cherry-pick Prometheus PR 15242

---

tsdb/index/postings.go

See: https://github.com/grafana/pir-actions/issues/238

[weekly-r314] Cherry-pick Prometheus PR 15242

---

tsdb/index/postings.go

See: https://github.com/grafana/pir-actions/issues/238

Cherry-pick Prometheus PR 15242

---

tsdb/index/postings.go

Cherry-pick of https://github.com/prometheus/prometheus/pulls/15427
Instead of allocating ListPostings pointers one by one, allocate a slice and take pointers from that. It's faster, and also generates less garbage (NewListPostings is one of the top offenders in number of allocations).

MemPostings: allocate ListPostings once in PFLM

---

tsdb/index/postings.go

Backporting https://github.com/prometheus/prometheus/pull/15426 while it's not in main yet (it's already in r317, r316, r315)

[weekly-r318] MemPostings: keep a map of label values slices

---

tsdb/index/postings.go

Cherry-pick of https://github.com/prometheus/prometheus/pull/15426 into weekly-r319, as main isn't up to date with prometheus/main yet.

[weekly-r319] MemPostings: keep a map of label values slices (#15426)

---

promql/engine.go
promql/engine_test.go

[Diff: prometheus/prometheus@19848bb... 94d5e0f](https://github.com/prometheus/prometheus/compare/19848bb...94d5e0f)
* https://github.com/prometheus/prometheus/pull/16718

Sync upstream prometheus @ 94d5e0f41cc2adf238e596353578d30b0c8dbf53

---

.github/workflows/merge-upstream-prometheus.yml

Adds success notifications when prometheus merges are successful to ensure the team is notified of PRs that need manual review and merging. This complements the existing conflict and error notifications, providing complete visibility into the merge workflow status.

actions update-prometheus: Add success notifications and mentions query-on-call
