- tsdb/block_test.go
- tsdb/blockwriter.go
- tsdb/compact_test.go
- tsdb/db.go
- tsdb/db_test.go
- tsdb/head.go
- tsdb/head_append.go
- tsdb/head_bench_test.go
- tsdb/head_test.go
- tsdb/querier_bench_test.go
- tsdb/querier_test.go
- tsdb/wal/wal.go
- web/api/v1/api_test.go
This PR writes OOO samples to a separate WAL with directory name `ooo_wal`.
It also fixes a bug in the ingestion.
> Write OOO samples to the WAL

- tsdb/db.go
- tsdb/head.go
- tsdb/head_test.go
- tsdb/head_wal.go
This is a follow up of https://github.com/grafana/mimir-prometheus/pull/181 and based on that PR. Once that is merged, the diff of this PR will be more digestible.
The changes look intimidating, but what I have done is:
1. Copy `loadWal` into `loadOOOWal` and remove all that is not required (i.e. keeping only samples replay and nothing to do with m-map chunks here yet).
2. Copy the `walSubsetProcessor` struct and its methods into `oooWalSubsetProcessor` and modify `oooWalSubsetProcessor.processWALSamples()` to write to the ooo chunk instead or the in-order chunk.
3. Some handling to identify if the replay error was for old WAL replay or the ooo WAL replay hence repair the appropriate WAL in db.go.
Things still missing and TODO in a follow up PR:
1. Add markers in the WAL as to when the …
> Replay OOO samples from the WAL

- tsdb/ooo_head_read.go
- tsdb/ooo_head_read_test.go
We thought about a few more cases that we think the Series() method
should be able to support. https://github.com/grafana/mimir-prometheus/pull/163#issuecomment-1088588894
This particular commit brings one where 4 chunks overlap in pairs in
decreasing order (the first case mentioned in the comment above)
I think we need to review the assumption we made about leaving the head chunk
max time set to maxint again because if the head chunk contains the oldest
samples in the interval then our algorithm fails.
In this commit I'm setting the maxtime to the headchunk's existing maxtime
instead.
> Add overlapping chunks in decreasing order test

- tsdb/chunks/head_chunks.go
- tsdb/chunks/head_chunks_test.go
- tsdb/chunks/old_head_chunks.go
- tsdb/chunks/old_head_chunks_test.go
- tsdb/head.go
- tsdb/head_test.go
This is a previous step towards releasing support for out of order chunks.
Memory mapped out of order chunks have a different encoding where the first bit is used to identified them as such. This decision would make it hard to rollback to a previous version of the TSDB once any OOO chunks have been memory mapped as it would lead to corruption errors when loading them into memory.
For this reason want to "discarding unknown encoding" chunks rather than failing. This would guarantee a safe rollback in case its necessary.
> Discard unknown chunk encodings

- cmd/promtool/tsdb.go
- tsdb/block.go
- tsdb/chunks/chunks.go
- tsdb/chunks/chunks_test.go
- tsdb/db_test.go
- tsdb/head.go
- tsdb/head_read.go
- tsdb/head_test.go
- tsdb/ooo_head.go
- tsdb/ooo_head_read.go
- tsdb/ooo_head_read_test.go
- tsdb/querier.go
- tsdb/querier_test.go
Relates to https://github.com/grafana/mimir-prometheus/issues/147
This PR implements the ChunkReader interface for the OOORangeHead and its called `OOOHeadChunkReader`. We're taking the structure from the [headChunkReader](https://github.com/grafana/mimir-prometheus/blob/62252d7f8a2fa0bd12681860b8c785c8005994d6/tsdb/head_read.go#L295) implementation and making the necessary changes for out of order.
- The interface has an important method called `Chunk()` and as we explained in https://github.com/grafana/mimir-prometheus/issues/147#issuecomment-1048064175 it needs to return a merged chunk from all chunks that overlap with it. Remember that in the OOOHead chunks may not be ordered in time.
- `Chunk()` makes use of a new function called `oooMergedChunk` which is the actual function that …
> Implement OOOHeadChunkReader

- tsdb/head_read.go
- tsdb/ooo_head_read_test.go
Following with the comment https://github.com/grafana/mimir-prometheus/issues/147#issuecomment-1098018961 and the fantastic work done by @Dieterbe  in https://github.com/grafana/mimir-prometheus/pull/190, this PR aims at bringing a few more unit tests to the out of order chunkreader implementation.
I'm thinking we could have this PR to bring tests for cases 1 to 4 (See https://github.com/grafana/mimir-prometheus/issues/147#issuecomment-1098018961 for more context). And then open a new one for cases 5 and 6 which are probably going to require some changes.
Also, note that the tests for Series() and Chunk() are slightly different since Chunk() requires actually appending samples to then make sure that the returned merged chunk does have the expected content.
> Covering more scenarios in out of order chunkreader

- tsdb/chunkenc/ooo.go
- tsdb/chunkenc/ooo_test.go
- tsdb/chunks/chunks.go
- tsdb/head_read.go
- tsdb/head_read_test.go
- tsdb/ooo_head_read.go
- tsdb/ooo_head_read_test.go
Alright! This PR brings query consistency in the case that the head keeps receiving samples in between Series() and Chunk() calls.
This came up from the scenarios @codesome thought about in https://github.com/grafana/mimir-prometheus/issues/147#issuecomment-1098018961 In particular case 5 and case 6.
<details>
<summary>Case 5 and 6 detailed:</summary>
Here starts the more interesting bit: ingesting more samples to the Head _after_ calling Series()
5) Current head gets an old sample and new sample after the Series() call
During Series()
```
Query Interval                                 [-----------------]
Chunk 0                                             [--------]
Chunk 1: Current Head                                      [--------]
```
Hence Series() would return chunk(0) based on …
> OOOChunkReader returns consistent queries after head keeps expanding

- tsdb/agent/db.go
- tsdb/chunks/head_chunks.go
- tsdb/compact.go
- tsdb/db.go
- tsdb/db_test.go
- tsdb/head.go
- tsdb/head_append.go
- tsdb/head_test.go
- tsdb/ooo_head_read.go
- tsdb/wal/wal.go
This adds compaction to generate multiple blocks out of OOO Head as per [this design doc](https://docs.google.com/document/d/1Kppm7qL9C-BJB1j6yb6-9ObG3AbdZnFUBYPNNWwDBYM/edit#heading=h.f3vr8krap9ta).
Since our aim is to support a relatively smaller OOOAllowance, the approach used here is to iterate over all possible block ranges for OOO Head and do compaction one at a time. For example if OOO Head had samples from 1.5h to 4.5h. It will try compaction for these 3 ranges one after another - [0h, 2h), [2h, 4h), [4h, 6) - while querying for all OOO series during each iteration.
But this step is done only once for all blocks together: 
At the start:
1. Cut a new WBL file and record the last WBL file seen at that time.
2. M-map all the active ooo chunks and keep track of the last m-map chunk …
> Add compaction for out of order samples in the Head

- tsdb/db.go
- tsdb/db_test.go
- tsdb/head.go
- tsdb/head_append.go
- tsdb/ooo_head.go
The way the querier reads from the tsdb is that it iterates all the existing blocks that overlap with the query interval (mint,maxt). And blocks can be 1) persistent blocks 2) in order head implementing block reader and now 3) out of order head implementing block reader :tada: 
What this PR does:
- Extends the db querier to also read form the out of order range head.
- Implement noop tombstone reader for the ooo range head. As stated in the design doc, we're not supporting tombstones for out of order.
- Add to the head a tracker for minOOOTime and maxOOOTime so that we know how much does the out of order head expand in time. 
- Note: We also need to make sure that this markers are properly tracked and updated during the ingestion of new ooo samples and compaction.
> Update db Querier to read from the ooo range head

- tsdb/db.go
- tsdb/db_test.go
Mimir uses ChunkQuerier to read from the TSDB. In https://github.com/grafana/mimir-prometheus/pull/222 we forgot to extend ChunkQuerier to also read form the out of order head. Both PRs are pretty similar.
This one also adds unit tests.
> Extend chunkquerier to read from the ooo head

- cmd/prometheus/main.go
- tsdb/db.go
Relates to https://github.com/grafana/mimir-ooo/issues/15
When out of order is enabled, compaction can potentially create overlapping blocks with the in order blocks. Because of this we want to make sure that Prometheus's option `AllowOverlappingBlocks` is always true if OOOAllowance is set.
> Set AllowOverlappingBlocks to true if ooo allowance is configured

- tsdb/db_test.go
- tsdb/head_append.go
- tsdb/head_test.go
This PR brings in multiple enhancements/fixes
1. Setting in-order mint/maxt of the Head properly.
2. Append ooo samples when no series exist for it in the Head. We take Head's maxt for the OOOAllowance check in that case.
3. Fix some m-map marker stuff. It was a TODO in the comment.
Unit tests exist for all of the fixes.
It will be easier to review 1 commit at a time instead of PR as a whole.
> Bunch of OOO Head enhancements and fixes

- storage/interface.go
- tsdb/head.go
- tsdb/head_append.go
In headAppender.Commit(), we always report any delta into the OOO
histogram, regardless of whether the sample was accepted or rejected,
and regardless of whether OOO is enabled or not.
In headAppender.Append(), we only reported the delta for OOO samples and
when OOO support was disabled.
The comprehensive behavior seems more useful, so switch to that.
+ cleanup exact overwrite case, don't increment the wrong metric
> clarify OOO metrics and comments

- model/labels/matcher_test.go
- model/labels/regexp.go
We can't remove the only Sub from regexp, since the contract for some operations says that there's at least one Sub, like OpStar or OpPlus.
In order to convert a single-sub element into a no-op, we change the operation to OpEmptyString. You can see the same trick being used by standard regexp code when simplifying `x{0}`: https://github.com/golang/go/blob/cf7ec0fa098a46c3b75cc3d625f5d7528fe6e984/src/regexp/syntax/simplify.go#L41-L46
Relates to https://github.com/grafana/mimir/issues/1866
> When removing start/end text op in regexp, don't break the contract.

- tsdb/db.go
- tsdb/db_test.go
- tsdb/head_read.go
Part of https://github.com/grafana/mimir-prometheus/pull/237
* Appending samples out of order and out of bound and working properly.
* No OOO artifacts are created when OOOAllowance is 0
* Including, no in-memory ooo chunk is created when ooo sample is discarded in this case
* Old metrics are incremented and not the new ones
> Write some unit tests for out of order

- tsdb/chunks/chunk_write_queue.go
This avoids wasting memory on the `c.chunkRefMap` by re-initializing it regularly. When re-initializing it, it gets initialized with a size which is half of the peak usage of the time period since the last re-init event, for this we also track the peak usage and reset it on every re-init event.
Very frequent re-initialization of the map would cause unnecessary allocations, to avoid that there are two factors which limit the frequency of the re-initializations:
* There is a minimum interval of 10min between re-init events
* In order to re-init the map the recorded peak usage since the last re-init event must be at least `10` (objects in `c.chunkRefMap`).
When re-initializing it we initialize it to half of the peak usage since the last re-init event to try to hit the sweet spot in the …
> Reduce chunk write queue memory usage

- tsdb/db_test.go
- tsdb/ooo_head_read.go
Covers this point from https://github.com/grafana/mimir-prometheus/issues/237
*  When compaction fails multiple times, m-map files and wbl is still cleared properly only after a successful compaction
The test makes sure that a failed compaction does not leave the
OOO Head corrupted. And eventually when a compaction works, the
blocks are created properly and the m-map files, WBL files and
the OOO Head are cleared properly.
> Add TestOOOCompactionFailure to test compaction failure

- tsdb/db_test.go
- tsdb/head_wal.go
Takes care of this point in https://github.com/grafana/mimir-prometheus/issues/237
*  Corruption in WBL and replay
Found a bug: we did not identify corruption in OOO WBL properly and always tried to repair old WAL with OOO WBL corruption error.
> Add test for corrupted OOO WBL repair and replay

- tsdb/chunks/chunk_write_queue.go
This PR fixes comments from post-merge review of https://github.com/grafana/mimir-prometheus/pull/247.
> Fix comments.

- tsdb/head_wal.go
Following with the improvement in https://github.com/grafana/mimir-prometheus/pull/264/commits/542b9ecdbd758009d52402f6a486d1237a6647b7 this commit aims to do the same for the OOO WBL replay.
> Reduce sleeping time when reading WBL

- cmd/prometheus/main.go
- config/config.go
- tsdb/db.go
- tsdb/db_test.go
- tsdb/head.go
- tsdb/head_append.go
- tsdb/head_test.go
- tsdb/ooo_head_read_test.go
To keep the logic simple, this is how the behaviour is for this feature (copy paste of comments):
```
// SetOutOfOrderAllowance updates the out-of-order allowance for the DB.
// This method must not be called concurrently.
// OOO enabled = oooAllowance > 0. OOO disabled = oooAllowance is 0.
// 1) Before: OOO disabled, Now: OOO enabled =>
//    * A new WBL is created for the head block.
//    * OOO compaction is enabled.
//    * Overlapping queries are enabled.
// 2) Before: OOO enabled, Now: OOO enabled =>
//    * Only the allowance is updated.
// 3) Before: OOO enabled, Now: OOO disabled =>
//    * Allowance set to 0. So no new OOO samples will be allowed.
//    * OOO WBL will stay and follow the usual cleanup until a restart.
//    * OOO Compaction and overlapping queries will remain …
```
> Enable changing OutOfOrderAllowance during runtime

- cmd/prometheus/main.go
- config/config.go
- tsdb/db.go
- tsdb/db_test.go
- tsdb/head.go
Removes the confusion over how the .Milliseconds() in the TSDB is used for OutOfOrderAllowance
> Remove the hack in config for OutOfOrderAllowance

- tsdb/block.go
- tsdb/compact.go
- tsdb/db.go
- tsdb/db_test.go
- tsdb/head_wal.go
Fixes https://github.com/grafana/mimir/issues/2238
> Avoid gaps in in-order data after restart with out-of-order enabled

- cmd/prometheus/main.go
- tsdb/db.go
- tsdb/db_test.go
- tsdb/head_append.go
This PR tries to simplify the logic around working of the `OutOfOrderTimeWindow`.
Current logic: If there is a series, time window is w.r.t. series' maxt. If the series does not exist, then it is w.r.t. the head's maxt. Problems with this is described in more detail in https://github.com/grafana/mimir-prometheus/issues/284
New solution: out of order time window now will always be taken w.r.t. the head's maxt. Making the logic as "if the sample cannot go in as in-order sample, then it should be within OutOfOrderTimeWindow from TSDB's maxt to inside out-of-order chunk".
This simple of logic of pinning it to a single time (i.e. head's maxt) will also make work with caches easier.
(This PR also removes 2 flags that are not required at Prometheus level)
> Simplify how OutOfOrderTimeWindow works

- storage/merge.go
- storage/merge_test.go
- tsdb/blockwriter.go
- tsdb/db.go
Closes https://github.com/grafana/mimir-prometheus/issues/298
Now `UnorderedChunkQuerier()` can be used in place of `ChunkQuerier()` in Mimir ingesters.
> Add support to query unmerged, unsorted chunks

- tsdb/head_append.go
We should only be observing the OOO delta in Append(), which covers the case of OOO disabled and enabled as well. If a sample was not OOO in Append() but OOO in Commit(), that is a rare case, and we can ignore it for now.
> Do not double count in OOO histogram

- tsdb/db.go
It is a lot of noise now that we expect overlapping blocks everytime there is out of order enabled.
> Do not warn on finding overlapping blocks, debug instead

- tsdb/db.go
- tsdb/db_test.go
We now replay WBL even if OOO is disabled, in which case WBL might be already initialised. This was not accounted for in ApplyConfig.
> Prevent panic with ApplyConfig

- .github/workflows/test.yml
This repository has a custom `test.yml` github workflow https://github.com/grafana/mimir-prometheus/blob/628f66d19afcef69b38fb6fc7b259e60a0ad1c31/.github/workflows/test.yml#L1 that has a redundant lint stage since there is a job from upstream that already does this https://github.com/grafana/mimir-prometheus/blob/d713e39865be0bd950404d1d0bb90a60ab4804e7/.github/workflows/golangci-lint.yml#L27-L30
So this PR is getting rid of the obsolete and redudant Lint job in test.yml
> Remove redundant CI Lint job

- tsdb/head_append.go
We're loading the time window once per each Append() call, plus once in the Commit(). While not extremely expensive, atomic operations are also not cheap.
Additionally, it makes sense to keep the window consistent for a single append.
> Load OutOfOrderTimeWindow only once per appender

- tsdb/db_test.go
- tsdb/head_test.go
- tsdb/ooo_head_read.go
- tsdb/ooo_head_read_test.go
OOOHeadIndexReader was using the headIndexReader PostingsForMatchers()
and LabelValues() implementation which lead to a very subtle bug that
led to wrong query results.
headIndexReader LabelValues() implementation checks if the query
timerange overlaps with the head maxt and mint and if it doesnt it
returns an empty list of values. Since this code was also used by the
ooo head it led to wrong results that we were not able to see in tests
because our queries where always from MinInt64 to MaxInt64. This commit
also adds a new test that performs multiple time range queries to make
sure this never happens again.
> Fix OOO Head LabelValues and PostingsForMatchers

- tsdb/db.go
- tsdb/db_test.go
If there was some OOO data on disk (in WBL or mmap chunks) that got replayed while OOO being disabled during a restart, we were not compacting that data. Hence never cleaning up the chunks_head directory of old files because those OOO mmap chunks share the chunks_head. This caused the disk to fill up after disabling OOO.
This PR fixes it by setting `db.oooWasEnabled` to true if some OOO data was replayed. `db.oooWasEnabled` is a way to signal that compaction needs to run on OOO data.
> Run OOO compaction after restart if there is OOO data from WBL

- rules/fixtures/rules_alerts.yaml
- rules/fixtures/rules_alerts2.yaml
- rules/manager.go
- rules/manager_test.go
When the ruler manager loads alerts while running it doesn't restore their state. For mimir this means that rules that get sharded to a ruler replica while it's running don't get their state restored. This PR adds an option to the ruler manager to always restore alert state when it load new or changed alerts. 
This behaviour does not affect loading groups which are unchanged. But it affects loading groups which have changed - either with new rules or with removed rules - those rules will get their state restored. 
This seems like a small change, so I think if this seems ok to us, I will propose to merge with with upstream.
related to https://github.com/grafana/mimir/issues/2888
> Add option to always restore the state of rules when loading

- tsdb/block.go
- tsdb/db.go
- tsdb/head.go
- tsdb/postings_for_matchers_cache.go
- tsdb/postings_for_matchers_cache_test.go
When out-of-order is enabled, queries go through both Head and OOOHead, and they both execute the same PostingsForMatchers call, as memSeries are shared for both.
In some cases these calls can be heavy, and also frequent. We can deduplicate those calls by using the PostingsForMatchers cache that we already use for query sharding.
The usage of this cache can skip a newly appended series in the results for the duration of the ttl.
> Allow forcing usage of PostingsForMatchersCache

- tsdb/head_read.go
- tsdb/index/postings.go
- tsdb/querier.go
- tsdb/querier_bench_test.go
Sometimes we receive a matcher for a label that doesn't match any postings. In that case, if it's an AND (_its_) matcher, we can stop the evaluation an return empty postings.
In order to do that properly, we should also return the empty postings everywhere properly.
I also considered adding an optional `Length()` or `IsEmpty()` method to some `Postings` implementation, but it seemed to be an overkill now (it might be useful in the future if we start sorting matchers by postings lengths though).
Benchmark results:
```
name                                                                      old time/op  new time/op  delta
Querier/Head/PostingsForMatchers/n="1"-16                                  321ns ± 1%   320ns ± 1%     ~     (p=0.266 n=8+8)
Querier/Head/PostingsForMatchers/n="X"-16 …
```
> Shortcut postings for matchers when empty postings are selected

- tsdb/async_block_writer.go
- tsdb/compact.go
- tsdb/compact_test.go
This PR fixes bug in `populateBlock` method. When `populateBlock` encountered error, it  could return with some async block writer were still running. This could then cause panic when closing index writer:
```
fatal error: concurrent map iteration and map write
goroutine 1155011084 [running]:
github.com/prometheus/prometheus/tsdb/index.(*Writer).writePostingsToTmpFiles(0xc108b21ce0)
/backend-enterprise/vendor/github.com/prometheus/prometheus/tsdb/index/index.go:821 +0xe8
github.com/prometheus/prometheus/tsdb/index.(*Writer).ensureStage(0xc108b21ce0, 0x3)
/backend-enterprise/vendor/github.com/prometheus/prometheus/tsdb/index/index.go:380 +0xba
github.com/prometheus/prometheus/tsdb/index.(*Writer).Close(0xc108b21ce0)
/backend-enterprise/vendor/github.com/prometheus/prometheus/tsdb/index/inde …
```
> stop-unfinished-writers-in-populateBlock

- model/rulefmt/rulefmt.go
- rules/fixtures/rules_with_alignment.yaml
- rules/manager.go
- rules/manager_test.go
This PR adds option to rule groups to align their evaluation time on evaluation interval.
This can be useful for example redundancy when two rulers are evaluating same rules -- if they both generate samples with same timestamp, only one sample will be written. But if one of rulers fails, the other one can keep on writing data.
(Our use case is different)
> Option to align rule group's evaluation time to interval

- model/rulefmt/rulefmt.go
- rules/fixtures/rules_with_alignment.yaml
- rules/manager.go
- rules/manager_test.go
This PR renames newly introduced align_execution_time_on_interval to use "evaluation" instead of "execution"
> Fix name of align_execution_time_on_interval option.

- model/labels/matcher.go
- model/labels/matcher_test.go
Sometimes label matchers know that they match values with a specific prefix. This information can be valuable in some downstream storage implementations.
> Expose `Matcher.Prefix()`

- cmd/compact/main.go
- tsdb/block.go
- tsdb/compact.go
- tsdb/compact_test.go
- tsdb/db.go
- tsdb/head.go
- tsdb/head_test.go
- tsdb/index/index.go
- tsdb/index/index_test.go
- tsdb/querier_bench_test.go
Instead of relying on `labels.Hash()`, which may change, have the caller pass in a shard function if required.
For most purposes `tsdb.Options.ShardFunc` is used, but the compactor may be created independently so `NewLeveledCompactorWithChunkSize` also takes a shard function parameter.
Regular Prometheus, which does not use block sharding, will have this parameter as nil.
> tsdb: make sharding function a parameter

- cmd/compact/main.go
- model/labels/sharding.go
- tsdb/block.go
- tsdb/compact.go
- tsdb/compact_test.go
- tsdb/db.go
- tsdb/head.go
- tsdb/head_append.go
- tsdb/head_read.go
- tsdb/head_test.go
- tsdb/index/index.go
- tsdb/index/index_test.go
- tsdb/querier_bench_test.go
This PR is a follow up of https://github.com/grafana/mimir-prometheus/pull/369. Instead of taking the sharding function as an option, we always use a "stable" hashing function which is guaranteed to not change over time.
> Hardcode the labels stable hash function instead of taking it as an option

- web/api/v1/api.go
- web/api/v1/api_test.go
- web/api/v1/codec.go
- web/api/v1/json_codec.go
- web/api/v1/json_codec_test.go
Duplicate of https://github.com/prometheus/prometheus/pull/11905 to unblock work on new query result payload format.
> Add extension point for returning different content types from API endpoints

- web/api/v1/api.go
- web/api/v1/api_test.go
- web/api/v1/json_codec_test.go
Continuation of #412 - ran into this issue while [implementing the new protobuf codec](https://github.com/grafana/mimir/commit/110a8b1617b7a3df3eff02e4ab456ca2bcba2645) in the querier.
> Extension point for returning different content types from API endpoints: expose QueryData so that implementations of Codec can use it.

- go.mod
- web/api/v1/api.go
- web/api/v1/api_test.go
- web/api/v1/codec.go
- web/api/v1/codec_test.go
- web/api/v1/json_codec.go
This resolves a concern with merging content negotiation to upstream (see https://github.com/prometheus/prometheus/pull/11905). 
It also allows us to override the default codec, which will allow us to use a custom codec that forbids encoding native histograms in the default JSON format between queriers and query frontends.
> Implement fully-featured content negotiation for API requests, and allow overriding the default API codec.

- web/api/v1/codec_test.go
This was incorrectly added as part of #428.
> Correct license header in `web/api/v1/codec_test.go`.

- model/labels/regexp.go
- model/labels/regexp_test.go
We have a customer running queries with case insensitive regular expression matchers similar to the following one:
```
label=~"(?i:(foo1|foo2|bar)"
```
When we receive such queries, we see almost 40% of ingesters CPU spent running the regex:
These types of regex are expected to be accelerated by `FastRegexMatcher`, in particular by `stringMatcherFromRegexp()` so why isn't the fast path triggered?
The reason is that a regex like `(?i:(foo1|foo2|bar)` is unrolled by the engine as an alternate **and** a concat because of the common prefix between `foo1` and `foo2`. `stringMatcherFromRegexp()` can handle the scenario the regex is case insensitive and has an alternate, but cannot handle the scenario it's case insensitive and has a concat too. In this PR I've done some changes to support the …
> Optimized FastRegexMatcher when the regex contains a case insensitive alternation made with concats too

- model/labels/regexp.go
- model/labels/regexp_test.go
I've added another fuzz test and found several issues related to how we optimize regexps when they contain the being/end text anchors inside. In the `main` version, we always remove being/end text anchors and we treat the regexp like if there were no anchors because of the assumption that any regex is anchored in Prometheus (which is true).
However, removing the begin/end text anchors from inside is not always safe. For example, if we remove the anchor from `^|x`, the resulting optimization is different because the empty string in one case is valid, while in the other case it's not.
After some experimentation, I found very difficult to correctly handle all begin/end text anchors, so in this PR I propose to not optimize a regexp if it contains them, unless they're really at tbe begin/end …
> Do not optimize regexps with begin/end text anchors inside

- model/labels/regexp.go
- model/labels/regexp_test.go
The change introduced in https://github.com/grafana/mimir-prometheus/pull/433 made me wonder if we're skipping the optimization for a significative % of queries that we were optimizing before that PR. I've extracted 300k of queries with regexp matchers from production and computed the % of optimized matchers before/after PR #443.  The good news is that among the 300k queries analyzed, the PR #433 reduces the % of optimized queries by very few (from 96.06% to 95.95%). The other good news is that https://github.com/grafana/mimir-prometheus/pull/430 actually increased the optimized queries by about a +3%.
In this PR I would like to upstream the code to run the analysis as a skipped test, so that it's ready if we want to re-run it in the future.
> Add TestAnalyzeRealQueries

- model/labels/regexp.go
- model/labels/regexp_test.go
When a regex matcher contains a long list of case insensitive alternations, the `FastRegexMatcher` optimise the matching using the `StringMatcher` returned by `stringMatcherFromRegexp()`. In particular, we will be in the case there are 1 or more nested `orStringMatcher` each one with multiple `equalStringMatcher`. All the `equalStringMatcher` are evaluated sequentially, so it's like iterating over a list of string values and compare each of them against the input.
In this specific case, when there are many alternations, it may be faster to put all values in a map and then lookup the values in the map to find if there's anyone of them matching. This is what this PR does.
To do it, I've introduced the function `optimizeEqualStringMatchers()` which optimise the output of …
> Optimized very long case insensitive alternations

- rules/alerting.go
This PR is to increase the valid until time in rules, since the current EndsAt time is not enough, It could cause resending notifications of alerts in certain cases (when temporary system failure or on system restart). See [Issue](https://github.com/grafana/mimir/issues/4118)
> Rules: Increase tolerance for missed iterations on alerts

- tsdb/block.go
- tsdb/db.go
- tsdb/querier_bench_test.go
While investigating the performance issues in the Mimir ingesters, due to some customer queries like `label=~".*"` where the postings cache could significantly help but it doesn't help as much as I expected,  I just realised that the settings I tuned for the postings cache in Mimir only apply to the **TSDB head**, but not the **TSDB compacted blocks** the customer queries also touch.
The TSDB block postings cache config is currently hardcoded to:
- TTL: 10s
- Cache size: 100
- Force: false
In this PR I propose to make the block postings cache configurable too. They're different config options, because I would like to set different settings (e.g. blocks are immutable, so TTL could be longer than 10s).
My plan is:
- Make blocks postings cache configurable in TSDB
- Expose these options in …
> Allow to configure compacted blocks postings for matchers cache

- tsdb/errors/errors.go
We need to be able to identify the errors that a multierror wraps. Especially in case of `context.Canceled`. This is the same implementation of that method as we do in github.com/grafana/dskit/multierror
Required to fix: https://github.com/grafana/mimir/issues/4564
> Implement Is() for multierrors

- go.mod
- go.sum
- model/labels/regexp.go
- model/labels/regexp_test.go
`NewFastRegexMatcher()` is typically very fast but there are some edge cases where parsing the regex may be very expensive. In this PR I propose to add an LRU cache on top of `NewFastRegexMatcher()` to avoid reparsing regex matchers that are frequently used. The size of the LRU is hardcoded to 10k entries.
To measure the overhead of the cache, I've created a new benchmark `BenchmarkNewFastRegexMatcher_CacheMisses` which measures `NewFastRegexMatcher()` on cache misses. I personally think the overhead is acceptable, considering the huge impact this cache could have on recurring complex regex matchers.
I've modified this benchmark to measure `NewFastRegexMatcher()` both with and without cache. Obviously the comparison with `main` shows am huge CPU reduction, but in practice this benefit …
> Cache optimized regexp matchers

- .github/dependabot.yml
This repo should be be as far as possible identical to upstream Prometheus, so we don't want these PRs.
This is what I found when I looked for instructions to disable [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file).
> Disable PRs from dependabot

- promql/bench_test.go
- promql/engine.go
- promql/engine_test.go
While investigating an issue with queries that use the `timestamp()` function with Mimir's chunks streaming (https://github.com/grafana/mimir/pull/5370), we discovered that the current special case handling for this function creates a new series iterator for each series for each time step in the query, as well as a new `MemoizedSeriesIterator` for each time step.
Not only does this break Mimir's chunks streaming (because creating a second iterator for a series requires reading chunks that we've already read past), it also turns out to be quite inefficient. Changing the special case for `timestamp()` to create and retain one iterator per series for the whole query has the following impact on the benchmark added in this PR:
```
goos: darwin
goarch: arm64
pkg: …
```
> Don't recreate iterator for each series on each timestep when evaluating a query with `timestamp()`

- web/api/v1/api_test.go
@bboreham noticed that `BenchmarkRespond` was missing a call to `InstallCodec` in  https://github.com/prometheus/prometheus/pull/11905#discussion_r1251255249.
> Add missing `InstallCodec` call to benchmark

- tsdb/querier.go
- tsdb/querier_bench_test.go
- tsdb/querier_test.go
This PR optimizes labelValues operation with matchers by iterating over all series matched by provided matchers, and collecting unique label values.
On its own this is pretty expensive operation, so this is only activated when number of matched series is tiny compared to number of all values for given label name.
Specifically, we require that queried label has at least 1000 unique label values, and matchers matched less than `(number of label values / 100)` series. (I did not do any analysis to compute these numbers, and I'm open to suggestions how to come with better ones.)
Benchmark for labelValuesForMatchers (updated for https://github.com/grafana/mimir-prometheus/pull/518/commits/e4d815d2383ba307c24a2cc72d55897d1e58179a):
```
goos: darwin
goarch: arm64
pkg: …
```
> Optimize `labelValuesWithMatchers` to fetch label values from selected series

- tsdb/addsymbol.go
- tsdb/addsymbol_stringlabels.go
- tsdb/symbols_batch.go
When compiled with `-tags stringlabels`, the names and values point into a larger block of memory containing all labels. Garbage-collection considers the entire block "live" if you point to a part of it, so the map ends up retaining all labels for (nearly) all series.
Cloning the string value avoids this problem, and we check first if the value is already in the map. Since the clone is more expensive, only do it when built with `-tags stringlabels`.
> compactor: avoid memory blow-up with stringlabels

- tsdb/head.go
- tsdb/head_bench_test.go
When a particular SeriesLifecycleCallback tries to optimize and run closer to the Head, keeping track of the HeadSeriesRef instead of the labelsets, it's impossible to handle the PostDeletion callback properly as there's no way to know which series refs were deleted from the head.
This changes the callback to provide the series refs alongside the labelsets, so the implementation can choose what to do.
> Pass ref to SeriesLifecycleCallback.PostDeletion (#12626)

- tsdb/querier.go
I'm not very comfortable with using an equality check on errors, but I'm copying the same code from Prometheus:
https://github.com/prometheus/prometheus/blob/f711d71aa8318dbb39522ac26f8ee77cc373f77b/tsdb/querier.go#L532-L533
> Check storage.ErrNotFound in labelValuesFromSeries

- tsdb/head_append.go
- tsdb/head_test.go
This cherry-picks 864da019cd036225b1763bc306384e5c85c75013 onto 16653689899c, so we can use the branch in Mimir
> Before cutting a new XOR chunk in case the chunk goes over the size limit, check that the timestamp is in order and not equal or older than the latest sample in the old chunk.
> cherry-pick "Fix duplicate sample detection at chunks size limit"

- tsdb/querier.go
- tsdb/querier_test.go
When cache was introduced, `LabelValues(matchers...)` could never be called with `concurrent=true` flag so it didn't make sense to use the cached call through the Head.
However, since the introduction of forced cache, we should use it, as even with `concurrent=false` the cache may be used.
> `LabelValues()` with matchers should use cache

- tsdb/postings_for_matchers_cache.go
- tsdb/postings_for_matchers_cache_test.go
Extract promise payload as a struct, to make size calculation easier.
> Refactor PostingsForMatcherCache promise

- model/labels/regexp.go
- model/labels/regexp_test.go
This PR builds on top of #536 and optimize for the ".?" case. I don't feel strong about this optimization, but we believe it's not too risky (from a correctness perspective), may be another bullet in our optimization arsenal.
Performance change for the queries containing ".?":
```
goos: darwin
goarch: amd64
pkg: github.com/prometheus/prometheus/model/labels
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
│ before-quest.txt │           after-quest.txt           │
│      sec/op      │   sec/op     vs base                │
FastRegexMatcher/fo.?-12             191.5n ± 1%   141.3n ± 1%  -26.21% (p=0.000 n=10)
FastRegexMatcher/foo.?-12            193.9n ± 3%   140.8n ± 2%  -27.40% (p=0.000 n=10)
FastRegexMatcher/f.?o-12             136.5n ± 2%   138.2n ± 2%   +1.28% (p=0.017 n=10) …
```
> Optimize .? in the FastRegexMatcher

- model/labels/regexp_test.go
The logic has changed, and we create a slice-based matcher for smaller number of alternations. This fixes the benchmark.
> Fix BenchmarkOptimizeEqualStringMatchers

- storage/merge.go
- storage/merge_test.go
If any iterator in a `chainSampleIterator` has a sample after the desired timestamp when `Seek()` is called, `Seek()` will not return `ValNone`. 
If some iterators have failed (ie. calling `innerIterator.Err()` returns a non-`nil` value) and others have not, this behaviour may hide errors from those iterators: callers of `Seek()` will not receive `ValNone` and therefore won't know to check `chainSampleIterator.Err()`.
`Next()` is susceptible to a similar issue if `Next()` is not called until the stream is completely exhausted. 
I'll submit this fix upstream once we've tested Mimir with it.
> Fix issue where `chainSampleIterator` can obscure errors

- rules/manager.go
This makes it easier to debug rule evaluation failures, and mirrors the pattern of behaviour for logs emitted by other parts of Mimir.
I'll submit this change upstream once we've tested Mimir with it.
> Include trace ID in log lines emitted during rule evaluation

- tsdb/db.go
Remove unused `ctx` argument from `DB.UnorderedChunkQuerier`. Also `DB.ChunkQuerier` doesn't have a `ctx` argument any longer.
Note that `DB.UnorderedChunkQuerier` doesn't exist upstream.
> DB.UnorderedChunkQuerier: Remove unused ctx argument

- tsdb/postings_for_matchers_cache.go
- tsdb/postings_for_matchers_cache_test.go
If the initial request for a set of matchers to `PostingsForMatchersCache.PostingsForMatchers()` cancels its context before the call returns, this cancellation can be cached, causing all subsequent calls to the cache for the same matchers to also return a context cancellation error while the cache entry is still live.
While this PR is sufficient to fix the problem above, there are some further improvements we could consider in the future:
* Should other kinds of errors also not be cached?
* If all waiting calls to `PostingsForMatchersCache.PostingsForMatchers()` have cancelled their context, should we cancel the context passed to the underlying `PostingsForMatchers` implementation?
> Fix issue where `PostingsForMatchersCache` can cache a context cancellation error

- promql/engine.go
- promql/functions.go
According to benchmarks, this is very inefficient for many rate queries, temporarily removing until we find a better way.
With before as without the removed code, and after as with:
```
goos: linux
goarch: amd64
pkg: github.com/prometheus/prometheus/promql
cpu: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
│ BenchmarkRangeQuery_before.txt │    BenchmarkRangeQuery_after.txt     │
│             sec/op             │   sec/op     vs base                 │
RangeQuery/expr=rate(a_hundred[1m]),steps=1000-16                      15.33m ± 2%   89.57m ± 3%  +484.36% (p=0.000 n=10)
│ BenchmarkRangeQuery_before.txt │      BenchmarkRangeQuery_after.txt      │
│              B/op              │     B/op       vs base                  │
RangeQuery/expr=rate(a_hundred[1m]),steps=1000-16 …
```
> Remove NewPossibleNonCounterInfo until it can be made more efficient

- storage/merge.go
- storage/merge_test.go
This PR fixes a similar issue to https://github.com/grafana/mimir-prometheus/pull/540, but this time for `concatenatingChunkIterator`: if a consumer of a `concatenatingChunkIterator` does not consume it all the way to the end (ie. until `Next()` returns `false`), it may not know to check for an error.
With this PR, `concatenatingChunkIterator.Next()` will instead begin returning `false` as soon as the current iterator reports an error.
> Fix issue where `concatenatingChunkIterator` can obscure errors.

- tsdb/postings_for_matchers_cache_test.go
Minor improvements to the `PostingsForMatchersCache` tests, no behavioral changes.
> PostingsForMatchersCache test improvements

- rules/group.go
This PR fixes an issue introduced in https://github.com/grafana/mimir-prometheus/pull/541 that was spotted as part of the upstream review: https://github.com/prometheus/prometheus/pull/13034#pullrequestreview-1703822504
> Don't drop rule name and index information from rule evaluation logs when adding trace ID

- tsdb/db_test.go
- tsdb/head_test.go
- tsdb/head_wal.go
- tsdb/ooo_head.go
- tsdb/ooo_head_read_test.go
Fixed a couple of bugs that were discovered while writing the test:
- mint for ooo chunk needed to be set when a new chunk was created
- first chunk was using the wrong previous appender
> Add counter reset test for mmapped OOO chunks

- tsdb/db_test.go
- tsdb/testutil.go
- Allow counter reset header to be compared
- Add timestamp value check
- Add timestamp to error message
> Improve requireEqualSamples

- tsdb/db_test.go
- tsdb/head_test.go
- tsdb/ooo_head_read_test.go
- tsdb/testutil.go
This PR expands OOO native histogram tests to include testing for gauge-type histograms. This is to check that gauge histograms, which do not have counter resets, are handled properly, with the correct CounterResetHint of histogram.Gauge type.
> Expand OOO native histogram tests to include gauge histograms

- model/labels/regexp.go
- model/labels/regexp_test.go
We're investigating some invalid query results which apparently happen when we have alternation regexp matchers (and so `FastRegexMatcher.SetMatches()` returns something). I have a weak theory that there may be a case when we manipulate the returned slice, thus polluting the cached `FastRegexMatcher`.
To avoid such headache, in this PR I do a simple change to always return a copy from `FastRegexMatcher.SetMatches()`.
> Ensure manipulating the returned FastRegexMatcher.SetMatches() doesn't pollute the matcher's internal state

- model/labels/regexp.go
- model/labels/regexp_test.go
cherry picks #571 
https://github.com/grafana/mimir-prometheus/pull/571/commits/986ca1a16a16bcc1a4285cd8f0d0b37572df55f0
https://github.com/grafana/mimir-prometheus/pull/571/commits/0a92839843f36d2d246fa7e73203c236408432de
> [mimir-release-2.11] Ensure manipulating the returned FastRegexMatcher.SetMatches() doesn't pollute the matcher's internal state

- model/labels/regexp.go
- model/labels/regexp_test.go
Backporting #571 for Mimir's 2.10 release branch.
> [mimir-release-2.10] Return a copy of strings from `FastRegexMatcher.SetMatches() `doesn'…`

- tsdb/postings_for_matchers_cache.go
- tsdb/postings_for_matchers_cache_test.go
Follow-up of https://github.com/grafana/mimir-prometheus/pull/553
Creating a new span for each promQL matcher for each query can end up being too verbose to navigate in grafana. This PR replaces the span with a trace log.
Overall starting a span was also expensive - according to profiles it's about 9% of the CPU of PostingsForMatchers and it's about 25% of the memory allocations. Adding events is about 2% of the CPU and ~5% of the allocations.
<details>
<summary>CPU Details</summary>
</details>
In addition to that it removes some log lines in `postingsForMatchersPromise` because I think they just log the same thing multiple times. I also removed some calls to AddEvent to amortize the cost of tracing further.
> PostingsForMatchersCache: don't create new spans, reduce logging verbosity

- model/labels/regexp.go
- model/labels/regexp_test.go
`FastRegexMatcher` ignores capture group by design. This is done calling `clearCapture()`. However, `clearCapture()` removes a single capture group. This means that when a regexp has nested capture groups (e.g. `((a|b))`) the optimization doesn't trigger because we remove the 1st capture group but not the 2nd (nested) one.
This PR fixes it. To clarify, this is not a logic bug, but we're missing the opportunity to optimize regexp with nested capture groups.
> Fix FastRegexMatcher to skip nested capture groups

- promql/engine_test.go
- util/teststorage/storage.go
This PR adds tests in engine_test.go to test counter resets when using the rate() function on native histograms.
> Add engine tests for OOO native histograms with counter resets

- model/labels/regexp.go
- model/labels/regexp_test.go
- tsdb/querier_bench_test.go
While testing a feature for Adaptive Metrics, I was surprised to find out that posting lookups for `foo=~"(bar|bar)"` are faster than `foo=~"bar"`. It turns out I introduced a performance regression in https://github.com/grafana/mimir-prometheus/pull/463.
When we added the `optimizeAlternatingLiterals` function, we subtly broke one edge case. A regexp matcher which matches a single literal, like `foo=~"bar"` used to return `bar` from `SetMatches()`, but currently does not. The implication is that the tsdb will first do a LabelValues call to get all values for `foo`, then match them against the regexp `bar`. This PR restores the previous behavior which is able to directly lookup postings for `foo="bar"` instead. In a random sample of 1M queries from a large dedicated cell, about 11% of …
> Fix regexp set matches for literal matchers

- tsdb/head_test.go
Test was failing due to ` 814 observations found in buckets, but the Count field is 1000: histogram's observation count should equal the number of observations found in the buckets (in absence of NaN)`. Updated test to generate a valid histogram for each sample rather than just updating the count.
> Fix OOO counter reset test

- tsdb/db_test.go
- tsdb/testutil.go
This PR adds tests for OOO Native Histograms with counter resets on the query side.
> Add OOO Native Histogram counter reset query tests

- tsdb/db_test.go
- tsdb/testutil.go
Add a test for when a series has samples with multiple encodings, including when the samples are out of order. Note that the behaviour is a bit weird when multiple encodings are committed together - float samples are always processed before histogram ones so sometimes histograms are marked as OOO when you might not expect them to be - see test comments for more details. I don't think this behaviour is worth changing as it shouldn't happen very often.
> Add multiple encoding test

- rules/alerting.go
- rules/alerting_test.go
- rules/dependency.go
- rules/dependency_test.go
- rules/fixtures/rules_multiple.yaml
- rules/fixtures/rules_multiple_independent.yaml
- rules/manager.go
- rules/manager_test.go
- rules/origin.go
- rules/origin_test.go
- rules/recording.go
- rules/recording_test.go
- rules/rule.go
This is a simplified version of https://github.com/grafana/mimir-prometheus/pull/584 which doesn't include the support to concurrently evaluate rules, but just analyse whether a Rule has dependents or dependencies and expose the info through RuleDetail. The content of `rules/dependency.go` and `rules/dependency_test.go` is a copy-paste from [Danny's PR](https://github.com/prometheus/prometheus/pull/12946).
Notes:
- The changes done in this PR have been designed to be as much isolated as possible from Prometheus code, in order to reduce the future conflicts when synching.
- Why did I call the fields / functions "**no** dependent/cy rules" (negative) instead of a positive "dependent/cy rules"? Reason is that I wanted the zero value to be the safest option (so zero value means "yes, there …
> rules.Manager: check whether a Rule has dependents or dependencies and expose it through RuleDetail

- cmd/prometheus/main_test.go
- cmd/prometheus/main_unix_test.go
- cmd/promtool/unittest_test.go
- documentation/prometheus-mixin/alerts.libsonnet
- promql/parser/lex_test.go
- rules/alerting.go
- rules/group.go
- rules/manager.go
- rules/manager_test.go
- rules/origin.go
- rules/origin_test.go
- rules/recording.go
- scrape/manager_test.go
- scrape/scrape_test.go
- scrape/target_test.go
- storage/remote/client.go
- tsdb/db_test.go
- tsdb/docs/format/index.md
- tsdb/fileutil/flock_test.go
- tsdb/head_test.go
- tsdb/index/index.go
- tsdb/index/index_test.go
- tsdb/index/postings_test.go
- tsdb/querier_test.go
- tsdb/wal_test.go
- tsdb/wlog/reader_test.go
- tsdb/wlog/wlog_test.go
- web/api/v1/api_test.go
- web/web_test.go
I've got another [Ruler PR merged upstream](https://github.com/prometheus/prometheus/pull/13527) and in this PR I'm re-syncing Prometheus in our mimir-prometheus. The changeset is very small. A part from the ruler changes, there's a change in TSDB which adds an extra check when writing blocks.
> Sync prometheus

- Makefile.common
- discovery/consul/consul_test.go
- discovery/file/file_test.go
- discovery/kubernetes/kubernetes_test.go
- discovery/manager_test.go
- discovery/marathon/marathon_test.go
- discovery/openstack/mock_test.go
- discovery/refresh/refresh_test.go
- discovery/zookeeper/zookeeper_test.go
- scripts/genproto.sh
- util/runtime/statfs_default.go
Sync with latest Prometheus upstream ([0853e52f4e735c4ad933cce429f4c83da649aca6](https://github.com/prometheus/prometheus/tree/0853e52f4e735c4ad933cce429f4c83da649aca6)).
This change set includes no user facing changes. Apart from tests, only the following changes:
* `make common-lint` is fixed on OSX ARM64 (Apple Silicon)
* `make proto` is fixed on OSX ARM64 (Apple Silicon)
> Sync with latest upstream

- tsdb/db.go
- tsdb/head.go
- tsdb/head_test.go
This PR introduces a new TSDB and head option: `TimelyCompaction`. This option, which defaults to `false`, allows compaction to happen if the min block range is no longer appendable, without requiring the head to exceed 1.5 times the chunk range, as the current behavior requires. When this option is not enabled, the current behavior applies. 
The goal of this setting is to allow compactions which might normally occur at a certain time, such as because of a previous early compaction, to still occur. For example: Consider a head with:
- minT=1:55
- maxT=3:01
If head compaction is attempted at 3:01, the current logic will prevent it since the head does not contain 1.5 times the block size. With `TimelyCompaction` enabled, the min-compactable block, which is from 1:00-2:00, is compactable …
> Add timely head compaction support

- promql/parser/parse.go
- promql/parser/parse_test.go
Cherry-pick upstream PR [fix: restore ability to match __name__ multiple times in selector](https://github.com/prometheus/prometheus/pull/13674). This restores the ability to have multiple matches on `__name__` between the curly braces in a Prometheus query.
> Cherry-pick "restore ability to match __name__ multiple times in selector"

- tsdb/head.go
- tsdb/head_append.go
- tsdb/head_test.go
Don't compact the Head block if there have not yet been any samples appended.
Previously, the logic for determining if the head should be compacted relied on the default values for min and max time and integer overflow when they were checked in `Head.compactable()`. The check in `Head.compactable()` effectively did `math.MinInt64 - math.MaxInt64` which overflowed and wrapped to `1`. Since `1` is less than `1.5` times the chunk range, compaction did not happen. This was the correct behavior but relying on overflow wrapping is surprising.
This change add a method for checking if the min and max time for the head is unset and uses it to short-circuit compaction in that case. It also replaces several explicit checks for the default value to determine if the head has not yet had any samples …
> TSDB: Don't compact the head block when empty

- model/labels/regexp.go
- model/labels/regexp_test.go
OpEmptyMatch is regex's nop operation, but it breaks some optimizations which aren't designed for a concatenation of multiple operations.
I saw a `pod=~"().*"` matcher in the wild and wondered whether it would be optimized, and was suprised to see that it wasn't.
> Remove OpEmptyMatch from regex concatenations

- .github/workflows/test.yml
Instead of defining a new job each time, we can just use a matrix. Useful since now we have the dedupelabels build aswell.
This also adds a test job for `dedupelabels` tag, which wasn't present before.
> Use matrix Github job to test all buildtags

- .github/workflows/test.yml
Using the pre-defined action should be faster than installing golang from scrach each time.
> Use setup-go 

- .github/workflows/test.yml
There's no much value in our fuzz tests if they're not ran in CI. This adds the configuration to run them for a minute.
> Fuzz in CI

- .github/workflows/container_description.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/test.yml
- .github/workflows/ui_build_and_release.yml
Upgrade to actions/checkout v4.1.4 in our GitHub workflows. I noticed we were using inconsistent versions of it (v2, v3, v4), so why not upgrade to the latest.
> GitHub Workflows: Upgrade to checkout v4.1.4

- promql/parser/printer.go
- promql/parser/printer_test.go
This brings the only new commit there's in upstream Prometheus:
> Fix `parser.VectorSelector.String()` with empty name matcher (#14015)
> Update upstream prometheus to: fix `parser.VectorSelector.String()` with empty name matcher (#14015)

- .github/workflows/test.yml
We don't want to wait 10m for the CI to merge a PR, but we can afford spending 10m fuzzying `main` branch.
This PR changes the `-fuzztime` arg dynamically to `10m` for `main` branch.
> Fuzz 10m for main branch

- promql/engine.go
- promql/engine_test.go
Same as https://github.com/prometheus/prometheus/pull/14083, but raising here so we can get this into Mimir quickly to resolve [a flaky test](https://github.com/grafana/mimir/actions/runs/9029074429/job/24810717724?pr=8100).
> promql: ensure series in matrix values returned for instant queries are sorted

- tsdb/index/index.go
- tsdb/index/postings.go
- tsdb/querier.go
Regex matching can be heavy if the regex takes a lot of cycles to evaluate.
> Check for context cancel before regex matching postings

- tsdb/db.go
- tsdb/db_test.go
db.CompactHead always truncates the memory and the WAL. I am working on something where I can skip this truncation in Mimir and save some computation. I would like to add this method here to experiment with it in Mimir.
> Add a db.CompactHeadWithoutTruncation function

- tsdb/postings_for_matchers_cache.go
- tsdb/postings_for_matchers_cache_test.go
The `PostingsForMatchersCache` has a comment that says:
```
// FIXME: do we need to cancel the call to postingsForMatchers if all the callers waiting for the result have
// cancelled their context?
```
During the weekend we learned the hard way that, yes, we should. The reason is that the underlying `PostingsForMatchers()` honor context cancellation, but when it's called through the single flight promise used by the cache, we run it with a new `context.Background()` and so it never gets canceled.
If the execution of the underlying `PostingsForMatchers()` takes a very long time (e.g. due to an insanely complex regexp), then it's undesirable keep it running if the request has been canceled. We prefer to cancel the `PostingsForMatchers()` execution.
This PR addresses it.
> Improve context cancellation handling in PostingsForMatchersCache

- cmd/prometheus/main.go
- cmd/promtool/backfill.go
- docs/configuration/configuration.md
- rules/manager_test.go
- tsdb/agent/db.go
- tsdb/agent/db_test.go
- tsdb/block.go
- tsdb/block_test.go
- tsdb/blockwriter.go
- tsdb/compact.go
- tsdb/compact_test.go
- tsdb/db.go
- tsdb/db_test.go
- tsdb/index/index.go
- tsdb/index/index_test.go
This PR merges upstream Prometheus, with following PRs:
* https://github.com/prometheus/prometheus/pull/14094
* https://github.com/prometheus/prometheus/pull/14143
* https://github.com/prometheus/prometheus/pull/14300
* https://github.com/prometheus/prometheus/pull/14302
PR https://github.com/prometheus/prometheus/pull/14143 has conflicts related to our sharding compactor. I've adapted `Compact` method to match updated description of this method -- specifically, it now returns `nil` if resulting block doesn't have any samples. Previously this returned empty `ulid.ULID`.
> Merge upstream Prometheus

- CHANGELOG.md
- storage/remote/otlptranslator/prometheusremotewrite/context.go
- storage/remote/otlptranslator/prometheusremotewrite/context_test.go
- storage/remote/otlptranslator/prometheusremotewrite/helper.go
- storage/remote/otlptranslator/prometheusremotewrite/histograms.go
- storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
- storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw_test.go
- storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
- storage/remote/write_handler.go
In the OTLP endpoint's translation layer, add checks for context cancellation/timeout every 128 times, similarly to what we do in e.g. `tsdb/index.MemPostings` code.
The motivation is that we've found that Mimir OTLP writes timing out continue the translation process, beyond the timeout. I suggest we test this improvement in Mimir first, and then eventually upstream it.
> OTLP: Check context error during translation

- storage/remote/write_handler_test.go
- tsdb/head_append.go
- tsdb/metadata.go
- tsdb/querier.go
Separate metalabel filtering from the querier and head appender, placing it into its own file.
> metalabels: move label matching in separate metadata.go

- model/labels/meta.go
- storage/remote/otlptranslator/prometheusremotewrite/helper.go
- storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
- storage/remote/write_handler_test.go
- tsdb/metadata.go
In the OTLP endpoint, add metadata labels for OTel resource attributes.
> OTLP: Add metadata labels for resource attributes

- tsdb/head_read.go
- tsdb/querier.go
There is a slight difference in how the methods for normal and stringlabels work. This PR fixes queries when stringlabels is used.
> Metalabels working with stringlabels

- tsdb/head.go
- tsdb/head_append.go
- tsdb/head_read.go
- tsdb/head_test.go
- tsdb/head_wal.go
r305 release is blocked by https://github.com/prometheus/prometheus/pull/14731. While Prometheus maintainers will  decide whether they prefer reverting or fixing but keeping the current design, we're going to revert the change in mimir-prometheus to unblock r305.
> Revert shard hash optimization

- storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
- storage/remote/otlptranslator/prometheusremotewrite/histograms_test.go
- storage/remote/otlptranslator/prometheusremotewrite/number_data_points_test.go
- storage/remote/otlptranslator/prometheusremotewrite/testutil_test.go
Add tests for OTLP translation logic, copied from https://github.com/open-telemetry/opentelemetry-collector-contrib, with attribution.
> OTLP Receiver: Add tests

- CHANGELOG.md
- cmd/prometheus/main.go
- storage/remote/otlptranslator/prometheusremotewrite/helper.go
- storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
- storage/remote/otlptranslator/prometheusremotewrite/histograms_test.go
- storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
- storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
- storage/remote/otlptranslator/prometheusremotewrite/number_data_points_test.go
- storage/remote/write_handler.go
- storage/remote/write_test.go
- web/api/v1/api.go
- web/api/v1/errors_test.go
- web/web.go
Modify the OTLP receiver to, if the `--created-timestamp-zero-ingestion` feature flag is true, convert data point start timestamps to Prometheus zero samples 1 millisecond before the sample itself, iff the following is true: The OTel start timestamp is greater than zero and equal to the data point timestamp.
Depends on #685.
> OTLP receiver: Convert start timestamps to Prometheus zero samples

- storage/remote/otlptranslator/prometheusremotewrite/helper.go
- storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
- storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
- storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw_test.go
- storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
- storage/remote/otlptranslator/prometheusremotewrite/number_data_points_test.go
- storage/remote/write_handler.go
- storage/remote/write_test.go
Relates to https://opentelemetry.io/docs/specs/otel/metrics/data-model/#resets-and-gaps and https://github.com/open-telemetry/opentelemetry-specification/issues/4184
While testing [our previously introduced feature](https://github.com/grafana/mimir-prometheus/pull/684) to introduce 0's at `ts-1` when an OTLP sample had `StartTimeUnixNano == sample.timestamp` we noticed that it was not working for some usages of the OTel SDK and connectors like the spanmetrics connector.
Later we found out the reason is that it's unclear to what value `StartTImeUnixNano` should be set to when there is a reset in a cumulative stream. The links at the beginning give you more context on what the spec says and then a reasonable ask by Arthur asking to have a StartTimeUnixNano initialized per series and to the …
> OTLP: Insert created timestamp if starttimestamp is within interval

- CHANGELOG.md
- cmd/prometheus/main.go
- storage/remote/otlptranslator/prometheusremotewrite/helper.go
- storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
- storage/remote/otlptranslator/prometheusremotewrite/histograms_test.go
- storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
- storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw_test.go
- storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
- storage/remote/otlptranslator/prometheusremotewrite/number_data_points_test.go
- storage/remote/otlptranslator/prometheusremotewrite/testutil_test.go
- storage/remote/write_handler.go
- storage/remote/write_test.go
- web/api/v1/api.go
- web/api/v1/errors_test.go
- web/web.go
Adds the following commits on top of r304:
These cover up to the initial fix and it is what you can find in [mimir-prometheus/weekly-r303](https://github.com/grafana/mimir-prometheus/commits/weekly-r303/) (Includes https://github.com/grafana/mimir-prometheus/pull/684 and https://github.com/grafana/mimir-prometheus/pull/685)
```
d57281fdd0277c518920d26e74306f8cdcbd0170
aa3c783d63fb1c8f25b3deae49cc6c7d6d4020b0
e676352a92a3b4c70180b451d5aa262bcc07f1e0
15b0f756a37e8a815368bebc2517a42398750ca0
12be21d1b0271c0baeca1c54f06ad14d7a3c38d9
```
These relate to the revised fix https://github.com/grafana/mimir-prometheus/pull/689
```
2a2019e280a3d2d298a18ca386ab118df2dfbbbd
0c21f747ce6a2c19434f26e478812528f6bf2ac3
cfbefed793d27678e28348898def5c6d975198cc
```
> Weekly r304 with created timestamp fix

- storage/remote/otlptranslator/prometheusremotewrite/helper.go
- storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
- storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
- storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
This PR enhances logging in OTEL translation code:
* it always logs a message when adding new zero-sample
* it includes metric type
* it now logs start_ts and sample_ts for all incoming samples and histograms.
The last point can generate a ton of messages when enabled.
> OTEL logging: add log when adding extra sample, log metric type too.

- storage/remote/otlptranslator/prometheusremotewrite/helper.go
- storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
- storage/remote/otlptranslator/prometheusremotewrite/histograms.go
Follow up PR to https://github.com/grafana/mimir-prometheus/pull/684 and https://github.com/grafana/mimir-prometheus/pull/689 where we add the same logic but for exponential histograms.
Unit tests included.
> OTLP: Convert Exponential histograms start timestamps into zero samples

- tsdb/db.go
- tsdb/ooo_head_read.go
- tsdb/ooo_head_read_test.go
- tsdb/querier_test.go
If the query overlaps the range currently undergoing compaction, we should only fetch chunks up to that time. Need to store that min time in `HeadAndOOOIndexReader`.
Cherry pick of https://github.com/prometheus/prometheus/commit/9215252221529d3ed56b5bf019e14acf20e4b618
> [BUGFIX] TSDB: Only query chunks up to truncation time (#14948)

- cmd/prometheus/main.go
- storage/interface.go
- tsdb/db.go
- tsdb/db_test.go
- tsdb/head.go
- tsdb/head_append.go
- tsdb/head_test.go
- tsdb/head_wal.go
- tsdb/ooo_head_read.go
- tsdb/ooo_head_read_test.go
- tsdb/ooo_head_test.go
- tsdb/testutil.go
There was one conflict because https://github.com/prometheus/prometheus/pull/14868 is not picked, but it only affects comment string. 
Includes:
- https://github.com/prometheus/prometheus/pull/14850  (small prepwork PR)
- https://github.com/prometheus/prometheus/pull/14546
> backport out-of-order native histograms pr14546 from upstream

- tsdb/index/postings.go
Go's built-in append() grows larger slices with factor 1.3, which means we do a lot more allocating and copying for larger postings. This shows up in profiles of WAL reading, for instance.
Cherry-pick of https://github.com/prometheus/prometheus/pull/14721
> Cherry-pick upstream #14721 [PERF] TSDB: Grow postings by doubling

- storage/remote/otlptranslator/prometheusremotewrite/helper.go
- storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
- storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
- storage/remote/write_handler.go
- storage/remote/write_test.go
- web/api/v1/api.go
- web/api/v1/errors_test.go
- web/web.go
Increasing valid threshold for inserting zero's at StartTimeUnixNano on OTLP Write requests.
The reason why we want to do this is that Grafana's $__rate_interval is typically 4 times the scrape interval so assuming an average DPM of 1 we could have the zero sample 4 minutes before the first sample. 
This is a small change that might help with usecases where samples are slightly delayed.
Also we've made this threshold configurable now. It defaults to 5 minutes but it can be overiden for special cases.
> OTLP: Increase valid created timestamp threshold to 5 minutes

- tsdb/db.go
Because we are reimplementing the `IndexReader` to fetch in-order and out-of-order chunks together, we must reproduce the behaviour of `Head.indexRange()`, which floors the minimum time queried at `head.MinTime()`.
Signed-off-by: Bryan Boreham <bjboreham@gmail.com>
(cherry picked from commit 91de19fbeffe19429f10c501a2f4364ae01711ea)
> [weekly-r307] [BUGFIX] TSDB: Don't read in-order chunks from before head MinTime

- tsdb/db.go
Because we are reimplementing the `IndexReader` to fetch in-order and out-of-order chunks together, we must reproduce the behaviour of `Head.indexRange()`, which floors the minimum time queried at `head.MinTime()`.
Signed-off-by: Bryan Boreham <bjboreham@gmail.com>
(cherry picked from commit 91de19fbeffe19429f10c501a2f4364ae01711ea)
> [r308] [BUGFIX] TSDB: Don't read in-order chunks from before head MinTime

- tsdb/db.go
Because we are reimplementing the `IndexReader` to fetch in-order and out-of-order chunks together, we must reproduce the behaviour of `Head.indexRange()`, which floors the minimum time queried at `head.MinTime()`.
Signed-off-by: Bryan Boreham <bjboreham@gmail.com>
(cherry picked from commit 91de19fbeffe19429f10c501a2f4364ae01711ea)
> [r309] [BUGFIX] TSDB: Don't read in-order chunks from before head MinTime

- tsdb/db.go
Because we are reimplementing the `IndexReader` to fetch in-order and out-of-order chunks together, we must reproduce the behaviour of `Head.indexRange()`, which floors the minimum time queried at `head.MinTime()`.
Signed-off-by: Bryan Boreham <bjboreham@gmail.com>
(cherry picked from commit 91de19fbeffe19429f10c501a2f4364ae01711ea)
> [r310] [BUGFIX] TSDB: Don't read in-order chunks from before head MinTime

- go.mod
- go.sum
Pick https://github.com/prometheus/prometheus/pull/15172
Ref: https://github.com/prometheus/client_golang/releases/tag/v1.20.5
Cherry-pick of upstream 4271670a829de5e8d6ff47089578eba0eada76e4
> chore(deps): update client_golang from 1.20.4 to 1.20.5

- storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
- storage/remote/otlptranslator/prometheusremotewrite/histograms.go
This PR undoes https://github.com/grafana/mimir-prometheus/pull/699 because OOO for NH is still WIP and this causes a lot of out of order errors. 
We can revert this PR when OOO NH is production ready again,
cc @lamida @krajorama @fionaliao
> OTLP: Disable handle starttime samples for Exponential Histograms

- tsdb/exemplar.go
- tsdb/exemplar_test.go
Fix data race conditions in `tsdb.CircularExemplarStorage`. Porting https://github.com/prometheus/prometheus/pull/15231.
> tsdb.CircularExemplarStorage: Avoid racing

- go.mod
- go.sum
Cherry-pick of https://github.com/prometheus/prometheus/pull/14897.
Upgrade github.com/googleapis/enterprise-certificate-proxy from v0.3.3 to v0.3.4, to fix the following error on OSX:
```console
✗ go mod tidy
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.3.3
verifying github.com/googleapis/enterprise-certificate-proxy@v0.3.3: checksum mismatch
downloaded: h1:G6q7VHBoU74wQHXFsZSLMPl0rFw0ZDrlZ3rt6/aTBII=
go.sum:     h1:QRje2j5GZimBzlbhGA2V2QlGNgL8G6e+wGo/+/2bWI0=
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```
See [issue](https://github.com/googleapis/enterprise-certificate-proxy/issues/127) for context. There are no …
> Upgrade github.com/googleapis/enterprise-certificate-proxy to v0.3.4

- tsdb/head_bench_test.go
- tsdb/index/postings.go
- tsdb/index/postings_test.go
Cherry-pick https://github.com/prometheus/prometheus/pull/15141.
When references are not added in order, we are sorting in place the tail of the postings list held by MemPostings, however the array backing that slice might already being used by some readers.
> Fix `MemPostings.Add` and `MemPostings.Get` data race

- tsdb/head_append.go
- tsdb/head_test.go
Cherry-pick https://github.com/prometheus/prometheus/pull/15142.
Two Appenders race when creating a series with a native histogram as the memSeries will be common and the lastHistogram field is written without lock.
Fix by:
Move writing memSeries lastHistogramValue and lastFloatHistogramValue
after series creation under lock.
The resulting code isn't totally correct in the sense that we're setting
these values before Commit() , so they might be overwritten/rolled back
later.
Also Append() of stale sample checks the values without lock, so there's
still a potential race.
The correct solution would be to set these only in Commit() which we
actually do, but then Commit() would also need to process samples in
order and not floats first, then histograms, then float histograms - which
leads to …
> bugfix: data race in head.Appender.AppendHistogram and Commit

- tsdb/postings_for_matchers_cache.go
- tsdb/postings_for_matchers_cache_test.go
Currently, `PostingsForMatchersCache.expire()` is called for every single `PostingsForMatchers()` call. If the cache is full, it's expected that there's always something to expire from the cache (1 in, 1 out). However, in a high concurrency environment, there's no need to call `expire()` **concurrently**. We just need 1 goroutine to cleanup stale or over-the-capacity cached entries.
In this PR I propose a simple solution to only 1 `expire()` execution at a time.
I've added a new benchmark:
```
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/tsdb
cpu: Apple M3 Pro
│  before.txt  │              after.txt              │
│    sec/op    │   sec/op     vs base                │
PostingsForMatchersCache_ConcurrencyOnHighEvictionRate-11   1653.0n ± 4%   335.1n ± 8%  -79.73% …
```
> Reduce PostingsForMatchersCache.expire() pressure on mutex

- rules/group.go
- rules/group_test.go
Port Prometheus PR [rules.NewGroup: Fix when no logger is passed](https://github.com/prometheus/prometheus/pull/15356), to fix segfaults in Mimir.
> rules.NewGroup: Fix when no logger is passed

- tsdb/index/postings.go
Relates to https://github.com/grafana/pir-actions/issues/238
This PR cherry-picks https://github.com/grafana/mimir-prometheus/pull/739 into the r309. This is so we could move forward with the mimir and GEM 2.14.x releases.
> [weekly-r309] Cherry-pick Prometheus PR 15242

- promql/engine_test.go
- promql/functions.go
- promql/promqltest/testdata/name_label_dropping.test
Cherry-pick PR [Fix round function not honoring delayed name removal flag](https://github.com/prometheus/prometheus/pull/15250), on request from @charleskorn. This harmonizes with v2.55.1, which Mimir is now based on, so that the `round` function drops the metric name.
> Fix round function not honoring delayed name removal flag

- promql/engine.go
- promql/promqltest/testdata/aggregators.test
- promql/promqltest/testdata/native_histograms.test
- promql/promqltest/testdata/operators.test
- util/annotations/annotations.go
Cherry-pick three native histograms fixes, [requested](https://github.com/grafana/mimir/pull/9948#issue-2670539860) by @charleskorn:
* https://github.com/prometheus/prometheus/pull/15245
* https://github.com/prometheus/prometheus/pull/15413
* https://github.com/prometheus/prometheus/pull/15414
> Cherry-pick native histograms fixes

- tsdb/index/postings.go
Cherry-picking https://github.com/grafana/mimir-prometheus/pull/750
While investigating lock contention on `MemPostings`, we saw that lots of locking is happening in `LabelValues` and
`PostingsForLabelsMatching`, both copying the label values slices while holding the mutex.
This adds an extra map that holds an append-only label values slice for each one of the label names. Since the slice is append-only, it can be copied without holding the mutex.
> [weekly-r314] MemPostings: keep a map of label values slices

- tsdb/block.go
- tsdb/head_read.go
- tsdb/index/index.go
- tsdb/index/index_test.go
- tsdb/index/postings.go
- tsdb/index/postings_test.go
- tsdb/ooo_head_read.go
- tsdb/postings_for_matchers_cache.go
- tsdb/postings_for_matchers_cache_test.go
- tsdb/querier.go
- tsdb/querier_test.go
Cherry-pick https://github.com/prometheus/prometheus/pull/14144, a querying performance improvement (see upstream PR for benchmark stats).
> [PERF] TSDB: Optimize inverse matching (#14144)

- tsdb/index/postings.go
While investigating lock contention on `MemPostings`, we saw that lots of locking is happening in `LabelValues` and `PostingsForLabelsMatching`, both copying the label values slices while holding the mutex.
This adds an extra map that holds an append-only label values slice for each one of the label names. Since the slice is append-only, it can be copied without holding the mutex.
> [weekly-r316] MemPostings: keep a map of label values slices

- tsdb/index/postings.go
Cherry-pick of https://github.com/grafana/mimir-prometheus/pull/750 into weekly-r315
While investigating lock contention on `MemPostings`, we saw that lots of locking is happening in `LabelValues` and
`PostingsForLabelsMatching`, both copying the label values slices while holding the mutex.
This adds an extra map that holds an append-only label values slice for each one of the label names. Since the slice is append-only, it can be copied without holding the mutex.
> [weekly-r315] MemPostings: keep a map of label values slices

- tsdb/index/postings.go
Cherry-pick of #750
While investigating lock contention on `MemPostings`, we saw that lots of locking is happening in `LabelValues` and
`PostingsForLabelsMatching`, both copying the label values slices while holding the mutex.
This adds an extra map that holds an append-only label values slice for each one of the label names. Since the slice is append-only, it can be copied without holding the mutex.
> [weekly-r317] MemPostings: keep a map of label values slices

- tsdb/db.go
- tsdb/db_test.go
For https://github.com/grafana/mimir/issues/9911
In order to reduce the number of blocks when a long OOO window is configured.
> Build 24h blocks for older OOO data

- tsdb/db.go
- tsdb/db_test.go
This is a follow up of https://github.com/grafana/mimir-prometheus/pull/751, making the feature opt-in
> Add a EnableBiggerOOOBlockForOldSamples option for the TSDB

- tsdb/chunkenc/float_histogram_test.go
- tsdb/chunkenc/histogram_meta.go
- tsdb/chunkenc/histogram_test.go
- tsdb/db_test.go
- tsdb/head_test.go
- tsdb/ooo_head_test.go
- tsdb/testutil.go
https://github.com/prometheus/prometheus/pull/15343
This is needed to ensure correctness when querying native histograms when merging chunks from different sources. This is especially important for out-of-order native histograms as you're more likely to have to merge chunks with overlapping timestamps.
I had to fix a couple of tests specific to mimir-prometheus - updated CounterReset headers to UnknownCounterReset
---------
> Cherry-pick: Always return unknown hint for first sample in non-gauge histogram chunk

- model/value/value.go
- storage/remote/otlptranslator/prometheusremotewrite/helper.go
- storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
- tsdb/db_test.go
- tsdb/head_append.go
- tsdb/head_test.go
When we want to add a zero at the start-time of the series, we don't know if a sample was previously added at that timestamp. So, use a special value which has the correct behaviour when it reaches TSDB.
Part of https://github.com/prometheus/prometheus/issues/14600
> TSDB: Add 'quiet zero' for Otel start-time handling

- tsdb/db.go
- tsdb/db_test.go
> [weekly-r318] Build 24h blocks for older OOO data + EnableBiggerOOOBlockForOldSamples option

- tsdb/db.go
- tsdb/db_test.go
> [weekly-r317] Build 24h blocks for older OOO data + EnableBiggerOOOBlockForOldSamples option

- tsdb/db.go
- tsdb/db_test.go
> [weekly-r316] Build 24h blocks for older OOO data + EnableBiggerOOOBlockForOldSamples option

- tsdb/db.go
- tsdb/db_test.go
> [weekly-r315] Build 24h blocks for older OOO data + EnableBiggerOOOBlockForOldSamples option

- .github/workflows/test.yml
This PR changes the order of steps in the CI workflow so that the code is checked out before running `setup-go`. This allows `setup-go` to cache Go dependencies listed in `go.mod`.
This change does not apply upstream as we use different CI workflows.
> ci: check out code before calling setup-go to enable dependency caching

- tsdb/index/postings.go
Cherry-pick of https://github.com/prometheus/prometheus/pull/15426 into weekly-r319, as main isn't up to date with prometheus/main yet.
https://github.com/grafana/mimir-prometheus/pull/778 was accidentally merged into main (which isn't a big deal, we're going to bring it through the usual merge process anyway)
> [weekly-r319] MemPostings: keep a map of label values slices (#15426)

- tsdb/head_append.go
- tsdb/head_test.go
Follow-up to https://github.com/grafana/mimir-prometheus/pull/766
"Quiet Zeros" are used to insert the starting sample for a counter. If the zero is out-of-order then we already have some data for the series, and we should have already handled the start value, so just drop the quiet zero.
There is one case not handled: if we receive (e.g. over OTLP) the second sample for a series before the first, and the first sample is nonzero and has time == startTime, then we will have inserted a zero erroneously at the start time.  If OOO is enabled we will then insert the correct value, and it is undetermined which value will come out at query time.  This case is not made worse by this PR.
> TSDB: Always drop 'quiet zeros' if out-of-order

- .github/workflows/test.yml
`actions/setup-go` creates and uses a single GitHub Actions cache entry for all jobs, but this is ineffective in our CI workflow:
* The `fuzz` job uses only [a subset](https://github.com/grafana/mimir-prometheus/actions/runs/12129753682/job/33819073754?pr=780#step:6:7) of dependencies, and so only those dependencies are downloaded to the runner-local cache. The `fuzz` job is far faster than the `test` job, so it wins the race to populate the cache entry for subsequent runs, but then the `test` job will always need to download a large number of dependencies.
* Similarly, the `fuzz` job only needs to build a subset of all packages, so populating the Go build cache from this means that the `test` job will always need to build a number of packages.
* The `test` job runs with different Go …
> Make caching in CI workflow more effective

- cmd/promtool/tsdb.go
- tsdb/block.go
- tsdb/block_test.go
- tsdb/blockwriter_test.go
- tsdb/compact.go
- tsdb/compact_test.go
- tsdb/db.go
- tsdb/db_test.go
- tsdb/index/index.go
- tsdb/index/index_test.go
- tsdb/index/labelvalues.go
- tsdb/index/labelvalues_test.go
- tsdb/querier_bench_test.go
- tsdb/querier_test.go
- tsdb/repair_test.go
This PR advances this fork closer to upstream Prometheus `main`, bringing in the changes from https://github.com/prometheus/prometheus/commit/140f4aa9aed6674c582dc603431a4aaa0c702cb7, which is the merge of https://github.com/prometheus/prometheus/pull/13567.
This merge had a number of conflicts. While I _believe_ I've merged this correctly given there were minimal conflicts in the tests and all tests are passing, carefully checking these changes would be appreciated.
Conflicts were in:
* `tsdb/block.go`
* `tsdb/compact.go`
* `tsdb/db.go`
* `tsdb/index/index.go`
* `tsdb/index/index_test.go`
* `tsdb/querier_bench_test.go`
> Merge upstream at 140f4aa

- tsdb/index/index.go
Comment hasn't been correct since
https://github.com/grafana/mimir-prometheus/pull/411
> index.go: fix comment

- tsdb/head_append.go
- tsdb/head_test.go
Reverts grafana/mimir-prometheus#773
We've detected an issue where NaNs filtered to the WAL and restarts caused an issue. We're reverting this PR and the one before it to revert the entire bug and have a stable main. Then we'll work again on it.
> Revert "TSDB: Always drop 'quiet zeros' if out-of-order"

- tsdb/querier.go
- tsdb/querier_test.go
Backporting https://github.com/prometheus/prometheus/pull/15684
We were appending to the wrong slice, so instead of removing values, we were adding them.
> [weekly-r321] Fix bug in lbl!~".+" shortcut (#15684)

- rules/group.go
- rules/manager.go
- rules/manager_test.go
* feat(ruler): Add new `RuleEvaluationTimeSum` field to groups
Coupled with a metric: `rule_group_last_rule_duration_sum_seconds`
This will give us more observability into how fast a group runs with or without concurrency
> (Backport to r321) rules: Add new `RuleEvaluationTimeSum` field to groups (#15672)

- tsdb/index/index.go
This reverts commit 4dacd7572a831f0ad8b83e785cb4da82be143a97, reversing changes made to 5e124cf4f2b9467e4ae1c679840005e727efd599.
We've linked https://github.com/prometheus/prometheus/pull/15455 to strong increase in Mimir compactor memory utilization. Therefore we need to revert it.
> Revert "Merge pull request #15455 from bboreham/compact-cache-symbols"

- tsdb/postings_for_matchers_cache.go
- tsdb/postings_for_matchers_cache_test.go
This makes it easier to understand the age of a cached entry, which is useful when debugging the behaviour of the cache.
> Include cache entry timestamp in trace events emitted by postings for matchers cache

- tsdb/postings_for_matchers_cache.go
- tsdb/postings_for_matchers_cache_test.go
Reverts grafana/mimir-prometheus#820
@pracucci pointed out in https://github.com/grafana/mimir/pull/10467#discussion_r1920420948 that this may make the cache ineffective in the case where computing the postings takes a long time.
> Revert "Include cache entry timestamp in trace events emitted by postings for matchers cache"

- tsdb/block.go
- tsdb/db.go
- tsdb/db_test.go
- tsdb/head.go
- tsdb/postings_for_matchers_cache.go
- tsdb/postings_for_matchers_cache_test.go
- tsdb/querier_bench_test.go
In this PR I propose two changes to PostingsForMatchers cache:
1. Check if the TTL for cached postings is still valid before returning it from cache, to fix a race condition that could happen between a goroutine running `expire()` and another one skipping the `expire()` execution because it's already in progress.
2. Add metrics to PostingsForMatchers cache, to have better visibility over it. This is something I wanted to do since a long time. The design I picked is to allow to pass the metrics struct as DB options, so that we can use 1 single struct for all per-tenant TSDBs in a Mimir ingester.
The following benchmark shows the difference betweeen:
- `01bb37aae`: the commit before https://github.com/grafana/mimir-prometheus/pull/734
- `6c2603082`: the commit at …
> Check cached postings TTL before returning from cache + metrics

- tsdb/postings_for_matchers_cache.go
- tsdb/postings_for_matchers_cache_test.go
In https://github.com/grafana/mimir-prometheus/pull/822 I've introduced metrics for the `PostingsForMatchers` cache. In this PR I'm extending the metrics to count evictions by reason.
Ref: https://github.com/grafana/pir-actions/issues/307
**Benchmarks**
```
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/tsdb
cpu: Apple M3 Pro
│ before.txt  │             after.txt             │
│   sec/op    │   sec/op     vs base              │
PostingsForMatchersCache/no_evictions-11                    639.1n ± 2%   636.2n ± 1%       ~ (p=0.394 n=6)
PostingsForMatchersCache/high_eviction_rate-11              10.66µ ± 0%   10.70µ ± 1%       ~ (p=0.071 n=6)
PostingsForMatchersCache_ConcurrencyOnHighEvictionRate-11   328.2n ± 1%   326.3n ± 3%       ~ (p=0.167 n=6)
geomean …
```
> Track evictions in the PostingsForMatchers cache

- tsdb/postings_for_matchers_cache.go
In https://github.com/grafana/mimir-prometheus/pull/822 @charleskorn suggested to log the `PostingsForMatchers` cache promise completion timestamp in the trace. I'm doing it in this PR. However, there's a small performance regression introduced by the extra span event (using epoch timestamp to reduce the regression):
```
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/tsdb
cpu: Apple M3 Pro
│ before.txt  │             after.txt              │
│   sec/op    │   sec/op     vs base               │
PostingsForMatchersCache/no_evictions-11                    637.3n ± 6%   705.8n ± 1%  +10.74% (p=0.002 n=6)
PostingsForMatchersCache/high_eviction_rate-11              10.67µ ± 1%   10.78µ ± 0%   +1.02% (p=0.002 n=6)
PostingsForMatchersCache_ConcurrencyOnHighEvictionRate-11 …
```
> Track PostingsForMatchers cached promise completion timestamp in trace

- rules/fixtures/alert_rule.yaml
- rules/fixtures/alert_rule1.yaml
- rules/fixtures/rules_alerts.yaml
- rules/fixtures/rules_alerts2.yaml
- rules/manager.go
- rules/manager_test.go
This PR steps us closer to being in sync with the latest upstream changes.
Diff: https://github.com/prometheus/prometheus/compare/0962d08...39d7242
The only change in this PR is https://github.com/prometheus/prometheus/pull/15669, which is a direct replacement for a similar change we had made in this fork in https://github.com/grafana/mimir-prometheus/pull/328.
To confirm there are no regressions, I ran the tests from #328 with the newly introduced `RestoreNewRuleGroups` option, and they passed. Given the upstream PR also introduced similar tests for this feature, I've therefore removed the tests added in #328.
> Sync upstream Prometheus at 39d7242

- CHANGELOG.md
- tsdb/agent/db.go
- tsdb/db_test.go
- tsdb/head.go
- tsdb/head_test.go
- tsdb/head_wal.go
- tsdb/wlog/checkpoint.go
- tsdb/wlog/checkpoint_test.go
- tsdb/wlog/watcher_test.go
cherry-pick of https://github.com/prometheus/prometheus/pull/16060
> TSDB: keep duplicate series records in checkpoints while their samples may still be present

- model/rulefmt/rulefmt.go
This is a cherry-pick of the two commits in https://github.com/prometheus/prometheus/pull/16252 that export `RuleGroupNode` and `RuleNode`. This missing export is currently blocking updates of mimir-prometheus -> mimir (see https://github.com/grafana/mimir/pull/10884).
> Cherry-pick alexweav:alexweav/validate-unexported

- CHANGELOG.md
- tsdb/head.go
- tsdb/head_test.go
- tsdb/head_wal.go
This cherry-picks a series of PRs that improve tracking and handling of duplicate series during WAL/WBL replay:
- https://github.com/prometheus/prometheus/pull/16166
- https://github.com/prometheus/prometheus/pull/16225
- https://github.com/prometheus/prometheus/pull/16231
- https://github.com/prometheus/prometheus/pull/16242
> Cherry-pick WAL/WBL replay improvements

- CHANGELOG.md
- tsdb/head.go
- tsdb/head_test.go
- tsdb/head_wal.go
This backports https://github.com/grafana/mimir-prometheus/pull/849 to the [version of mimir-prometheus currently used in mimir r334](https://github.com/grafana/mimir/blob/r334/go.mod#L302)
> Backport #849 to mimir r334

- README.md
- go.mod
- internal/tools/go.mod
- storage/remote/client.go
This brings changes from prometheus/prometheus up to 2025-03-26 commit https://github.com/prometheus/prometheus/commit/de399eb09c90ba4e643b58bb998b0c158892d72e
Diff: https://github.com/prometheus/prometheus/compare/bd5b2ea9...de399eb
No merge conflicts.
Included PRs:
- https://github.com/prometheus/prometheus/pull/16323
- https://github.com/prometheus/prometheus/pull/16322
- https://github.com/prometheus/prometheus/pull/16320
- https://github.com/prometheus/prometheus/pull/16319
- https://github.com/prometheus/prometheus/pull/15093
No major changes.
> Sync with upstream up to de399eb09 (2025-03-26)

- tsdb/head_wal.go
It seems that sometimes we end up with sample records written to the WAL before their corresponding series record. Because the WAL is processed in-order, these leads to the replay reporting unknown series references. It's unclear whether this explains ALL of the instances of unknown series references we see in our cluster, so this PR adds some logging/metrics to let us determine that.
I'm making this change in mimir-prometheus rather than prometheus itself because it's purely a diagnostic thing for now. Impact should be minimal, as this only runs when we already know we have unknown series refs.
> Log instances where WAL replay detect unknown series references, but the series records are found later in the WAL segment

- tsdb/head.go
- tsdb/head_test.go
- tsdb/head_wal.go
This builds on https://github.com/grafana/mimir-prometheus/pull/861 to also track if a sample record is written before its series record into a completely different WAL segment. Hopefully this will explain the remaining instances of unknown series refs we see.
I'm keeping this to mimir-prometheus because it is still just diagnostic information.
> Log instances where WAL replay detect unknown series references, but the series records are found in a later WAL segment

- .promu.yml
- model/labels/labels.go
- model/labels/labels_stringlabels.go
- model/labels/sharding.go
- model/labels/sharding_stringlabels.go
- tsdb/agent/series_test.go
- tsdb/head_test.go
This temporarily reverts https://github.com/prometheus/prometheus/pull/16436, which is causing issues for one of the internal projects that pulls in this project through `grafana/mimir`, as this internal project has not been updated to work with `stringlabels`.
Projects such as Mimir and GEM that explicitly set `stringlabels` will continue to receive `stringlabels`, as they did before.
> Revert `stringlabels` default

- tsdb/block.go
- tsdb/head.go
- tsdb/postings_for_matchers_cache.go
- tsdb/postings_for_matchers_cache_test.go
I'm not adding an attribute here because propagating it there would increase the size of each entry and we'd fit fewer entries in the cache (a unit test failed because of this too)
https://github.com/grafana/mimir-prometheus/blob/14aa68b0ec7433f31a2f152dedf857a5b9c2982d/tsdb/postings_for_matchers_cache.go#L188-L192
> PostingsForMatchersCache: add block ID attribute to trace events

- storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
Translation of OTLP non-monotonic sum metrics has been broken in Prometheus since https://github.com/prometheus/prometheus/pull/16626, because [translatorMetricFromOtelMetric](https://github.com/prometheus/prometheus/pull/16626/files#diff-1e76309731ff41b269672516ed66c8848b751e0d48a596dc8c15a4dda9a2cbecR78) associates sum metric monotonicity with cumulative aggregation temporality. There is no such connection, one should instead (as before that PR) check whether the sum is monotonic. I'm proposing a fix in this PR, and have written a corresponding test in Mimir (see [PR](https://github.com/grafana/mimir/pull/11810)), as a guard against this reoccurring.
I will make an upstream PR, including tests, after this and the Mimir PR get merged.
> OTLP receiver: Fix conversion of non-monotonic sums

- model/labels/labels.go
- model/labels/labels_dedupelabels.go
- model/labels/labels_dedupelabels_test.go
- model/labels/labels_slicelabels_test.go
- model/labels/labels_stringlabels.go
- model/labels/labels_stringlabels_test.go
Bring https://github.com/prometheus/prometheus/pull/16717 to mimir-prometheus so that we can use it in https://github.com/grafana/mimir/pull/11683 earlier.
> Add ByteSize method for Labels

- .github/workflows/merge-upstream-prometheus.yml
I can't explain it but for some reason this command skipped two commits. I suspect it's to do with creating the PR - maybe it checks back out the base branch after creating a PR? IDK
Resetting to HEAD~1 from 9b2459804 should lead to 609b9c7c04c1ab675ebff483567caf3a3595818f not to d3be9d0e3
From https://github.com/grafana/mimir-prometheus/actions/runs/16172079971/job/45647987237:
```
Run # Force-push to HEAD~1 to close the existing PR (removes the empty commit, leaving no commits)
git push --force origin HEAD~1:bot/main/merge-upstream-main-202507091426
shell: /usr/bin/bash -e {0}
env:
APP_ID: ***
PRIVATE_KEY: ***
...
PULL_REQUEST_NUMBER: 931
To https://github.com/grafana/mimir-prometheus
+ 9b2459804...d3be9d0e3 HEAD~1 -> bot/main/merge-upstream-main-202507091426 (forced update)
```
So just …
> merge-upstream-prometheus: close PR by force-pushing to base branch instead of HEAD~1

- tsdb/block.go
- tsdb/db.go
- tsdb/db_test.go
- tsdb/head.go
- tsdb/head_read.go
- tsdb/index/index.go
- tsdb/index/index_test.go
- tsdb/index/lookup.go
- tsdb/index/lookup_test.go
- tsdb/ooo_head_read.go
- tsdb/querier.go
- tsdb/querier_bench_test.go
- tsdb/querier_test.go
This PR integrates the scan matchers feature from prometheus/prometheus#16835 into our mimir-prometheus fork.
In the Prometheus TSDB, matchers are always used to query the index. There are some cases where skipping those matchers from the index and then applying them on the retrieved series from the block is less resource intensive. 
This is the plan we have in Mimir to solve this: https://github.com/grafana/mimir/issues/11916
In this PR I'm introducing the concept of **scan matchers**. Unlike to **index matchers** (aka just "matchers" today), scan matchers are used to filter out series after they have been retrieved from the block.
The core of this PR adds a new method to the `IndexReader`, called `IndexLookupPlanner() index.LookupPlanner`. An `index.LookupPlanner` partitions the …
> tsdb index: introduce scan matchers

- .github/workflows/vendor_reviewer.yml
apparently we need to be explicit. follow-up of #927 
https://github.com/grafana/mimir-prometheus/actions/runs/16645042297/job/47103599261?pr=951
```
--merge, --rebase, or --squash required when not running interactively
```
> vendor_reviewer.yml: choose "--merge" merge

- tsdb/index/postings.go
- tsdb/postings_for_matchers_cache.go
- tsdb/postings_for_matchers_cache_test.go
At present, the postings for matchers cache tracks bytes for entries, which consist of the key + promise, and evicts cache entries when the max bytes are exceeded. But the size of the promise is shallow and doesn't include the size of the internal `PostingsCloner`. 
This PR improves the way that the postings cache size is tracked to include `PostingsCloner` usage. This PR also exposes the recently added entries and bytes metrics for non-shared caches.
With the same configuration, postings cache entries are more likely to expire due to hitting the max bytes, since this will be more accurate than previously.
> Improve postings cache size calculation and metrics

- tsdb/block.go
- tsdb/db.go
- tsdb/head.go
- tsdb/head_read.go
- tsdb/index/index.go
- tsdb/index/index_test.go
- tsdb/ooo_head_read.go
- tsdb/querier_bench_test.go
Refactor index lookup planner to use function-based approach instead of static planners.
- Replace `IndexLookupPlanner` with `IndexLookupPlannerFunc` in `Options` and `HeadOptions` 
- `OpenBlockWithOptions` takes function, calls it once when block opens, caches result
- Head calls function periodically during stats updates, stores in atomic pointer
1. Create specialized planners based on block metadata (ULID, time range, etc.)
2. Use different statistics for different blocks when making query planning decisions
3. Optimize query execution on a per-block basis rather than using global statistics
Related to https://github.com/grafana/mimir/issues/12432
> Add IndexLookupPlannerFunc to TSDB Options

- .github/workflows/test.yml
This PR fixes an issue with the Slack notification messages sent after a failed CI run, where the message contains `**test (stringlabels)**` instead of `test (stringlabels)` appearing in bold.
> Fix formatting of Slack message for test failures

- tsdb/db.go
- tsdb/postings_for_matchers_cache.go
This change adds support for providing a postings cache factory for head and compacted blocks when opening a DB, rather than requiring them to be constructed internally. This allows the same factory to be used, if desired, across DBs.
```release-notes
NONE
```
> Support providing postings cache factory instances when opening a DB
